Repository vmware/singleton, pull requests merged in 2019-08, with the labels that each got.

#26 [skip CI] initialize travis
  .travis.yml
Labels: cla-not-required

#24 Add CI for angular-client
  .travis.yml
Labels: cla-not-required

#29 Update README
  README.md
Labels: cla-not-required

#31 Update host address in jscoresdk
  autotest/client/jscoresdk/utils/constants.ts
Labels: cla-not-required

#32 [skip CI] update contributing file.
  CONTRIBUTING.md
Labels: cla-not-required

#34 Update jscoresdk test case to temporary remove 2 block case
  autotest/client/jscoresdk/data/pluraldata.xlsx
Labels: cla-not-required

#23 Add CI for js-core-sdk
  .travis.yml
Labels: cla-not-required

#36 Change language from en-US to en.
  autotest/client/jscoresdk/utils/constants.ts
Labels: cla-not-required

#38 comment unstable test
  .travis.yml
  src/test/java/com/vmware/vip/i18n/MessageCache2Test1.java
Labels: cla-not-required

#35 remove '[FATAL_ERROR]' from log
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/product/ProductService.java
Labels: cla-not-required

#39 create code owner file
  CODEOWNERS
Labels: cla-not-required

#44 [skip CI] Revise CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-not-required

#45 Update g11n-js-client branch CI to fit sonar scan in pull request
  .travis.yml
Labels: cla-not-required

#37 Enable sonar scan for angular client
  .travis.yml
  config/karma.conf.js
Labels: cla-not-required

#78 [skip ci] create docs for pages
  docs/README.md
Labels: cla-not-required

#80 Resolve security issues reported on github
  g11n-ws/ui/vis-web/.angular-cli.json
  g11n-ws/ui/vis-web/.editorconfig
  g11n-ws/ui/vis-web/.gitignore
  g11n-ws/ui/vis-web/.travis.yml
  g11n-ws/ui/vis-web/CODE_OF_CONDUCT.md
  g11n-ws/ui/vis-web/CONTRIBUTING.md
  g11n-ws/ui/vis-web/Clarity Seed_LICENSE_MIT.txt
  g11n-ws/ui/vis-web/Clarity Seed_NOTICE.txt
  g11n-ws/ui/vis-web/README.md
  g11n-ws/ui/vis-web/e2e/app.e2e-spec.ts
  g11n-ws/ui/vis-web/e2e/app.po.ts
  g11n-ws/ui/vis-web/e2e/tsconfig.json
  g11n-ws/ui/vis-web/karma.conf.js
  g11n-ws/ui/vis-web/logo.png
  g11n-ws/ui/vis-web/package-lock.json
  g11n-ws/ui/vis-web/package.json
  g11n-ws/ui/vis-web/protractor.config.js
  g11n-ws/ui/vis-web/src/app/about/about.component.html
  g11n-ws/ui/vis-web/src/app/about/about.component.scss
  g11n-ws/ui/vis-web/src/app/about/about.component.spec.ts
  g11n-ws/ui/vis-web/src/app/about/about.component.ts
  g11n-ws/ui/vis-web/src/app/app.component.html
  g11n-ws/ui/vis-web/src/app/app.component.scss
  g11n-ws/ui/vis-web/src/app/app.component.spec.ts
  g11n-ws/ui/vis-web/src/app/app.component.ts
  g11n-ws/ui/vis-web/src/app/app.module.ts
  g11n-ws/ui/vis-web/src/app/app.routing.ts
  g11n-ws/ui/vis-web/src/app/home/home.component.html
  g11n-ws/ui/vis-web/src/app/home/home.component.scss
  g11n-ws/ui/vis-web/src/app/home/home.component.spec.ts
  g11n-ws/ui/vis-web/src/app/home/home.component.ts
  g11n-ws/ui/vis-web/src/app/index.ts
  g11n-ws/ui/vis-web/src/environments/environment.prod.ts
  g11n-ws/ui/vis-web/src/environments/environment.ts
  g11n-ws/ui/vis-web/src/favicon.ico
  g11n-ws/ui/vis-web/src/images/clarity_logo.svg
  g11n-ws/ui/vis-web/src/index.html
  g11n-ws/ui/vis-web/src/main.ts
  g11n-ws/ui/vis-web/src/polyfills.ts
  g11n-ws/ui/vis-web/src/styles.css
  g11n-ws/ui/vis-web/src/test.ts
  g11n-ws/ui/vis-web/src/tsconfig.json
  g11n-ws/ui/vis-web/src/typings.d.ts
  g11n-ws/ui/vis-web/tslint.json
  g11n-ws/ui/vis-web/typings.json
Labels: cla-not-required

#73 Add dev guideline for Singleton service and java client
  CONTRIBUTING.md
  g11n-ws/docs/developer_guide_javaclient.md
  g11n-ws/docs/developer_guide_service.md
  g11n-ws/docs/img/intellij_build.png
  g11n-ws/docs/img/intellij_import.png
  g11n-ws/docs/img/intellij_run.png
  g11n-ws/docs/img/intellij_runl10n.png
Labels: cla-not-required

#97 Add description for signature
  CONTRIBUTING.md
Labels: cla-not-required

#98 Add sonar coverage exclusions
  .travis.yml
Labels: cla-not-required

#99 Using latest vip client config file in testing
  autotest/client/java/resource/vipconfig.properties
Labels: cla-not-required

#100 Add node_modules to sonar scan exclusion as it only has dependencies download from npmjs registry
  .travis.yml
Labels: cla-not-required

#109 Add welcome information to contributing guide.
  CONTRIBUTING.md
Labels: cla-not-required

#110 Fix typo
  CONTRIBUTING.md
Labels: cla-not-required

#114 Update Quality Gate for js core sdk and angular client
  sonar/quality_gates/angular-client.json
  sonar/quality_gates/js-core-sdk.json
Labels: cla-not-required

#116 Fix bug when query the memory cache
  src/services/core.service.ts
Labels: cla-not-required

#120 add gradle wrapper
  autotest/client/java/gradle/wrapper/gradle-wrapper.jar
  autotest/client/java/gradle/wrapper/gradle-wrapper.properties
  autotest/client/java/gradlew
  autotest/client/java/gradlew.bat
Labels: cla-not-required

#124 Exclude unit test coverage calculation for sample of js-core-sdk
  .travis.yml
Labels: cla-not-required

#133 Exclude samples and auto generated middle js and d.ts from sonar scan
  .travis.yml
Labels: cla-not-required

#117 Enable withCredentials
  samples/server/express/i18n/i18nHandler.js
  src/configuration.ts
  src/loader.ts
  src/services/core.service.ts
  test/plugins.mock.ts
Labels: area/js-client, cla-not-required

#128 Upgrade jackson-databind from 2.9.9 to 2.10.0.pr1 and Upgrade swagger-ui
  g11n-ws/build.gradle
  g11n-ws/modules/md-restful-api-i18n/build.gradle
  g11n-ws/modules/md-service-authen/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-i18n/lib/i18n-swagger-common-2.5.0.jar
  g11n-ws/vip-manager-i18n/lib/i18n-swagger-ui-2.5.1.jar
  g11n-ws/vip-manager-i18n/lib/i18n-swagger2-2.5.0.jar
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/SwaggerConfig.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/Swagger2ToDocTest.java
Labels: cla-not-required

#101 Add the static pages localization sample.
  samples/client/js/.babelrc
  samples/client/js/README.md
  samples/client/js/assets/vmware.png
  samples/client/js/html/example.html
  samples/client/js/index.js
  samples/client/js/package-lock.json
  samples/client/js/package.json
  samples/client/js/src/config.js
  samples/client/js/src/i18n.utils.js
  samples/client/js/src/source.l10n.js
  samples/client/js/src/translations/translation_zh.json
  samples/client/js/test/i18n.utils.test.js
  samples/client/js/webpack.config.js
Labels: area/js-client, cla-not-required

#90 Support making build through gradle wrapper
  .travis.yml
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: area/java-client, cla-not-required

#27 Change output from System.out to logger so that all output is in the log file. Change log file encoding to UTF-8.
  README.md
  src/test/java/com/vmware/vip/i18n/BaseTestClass.java
  src/test/java/com/vmware/vip/i18n/DateFormatUtilTest.java
  src/test/java/com/vmware/vip/i18n/FormatTest.java
  src/test/java/com/vmware/vip/i18n/LocaleTest.java
  src/test/java/com/vmware/vip/i18n/MessageCache2Test1.java
  src/test/java/com/vmware/vip/i18n/MessageCache2Test2.java
  src/test/java/com/vmware/vip/i18n/MessageCacheTest1.java
  src/test/java/com/vmware/vip/i18n/MessageCacheTest2.java
  src/test/java/com/vmware/vip/i18n/MessageFormatTest.java
  src/test/java/com/vmware/vip/i18n/NumberFormatUtilTest.java
  src/test/java/com/vmware/vip/i18n/PersistantCacheTest.java
  src/test/java/com/vmware/vip/i18n/PluralFormatTest.java
  src/test/java/com/vmware/vip/i18n/TranslationMessage2Test.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
  src/test/resources/log4j.properties
Labels: cla-not-required

#143 Support adding extra headers to HTTP request
  build.gradle
  src/main/java/com/vmware/vipclient/i18n/base/HttpRequester.java
  src/main/java/com/vmware/vipclient/i18n/base/VIPService.java
  src/test/java/com/vmware/vip/i18n/HttpRequesterTest.java
Labels: cla-not-required

#142 update the build script for store translations bundles in AWS S3
  g11n-ws/gradle.properties
  g11n-ws/vip-manager-i18n/build.gradle
Labels: cla-not-required

#150 Fix unit test error of header parameters test cases
  src/test/java/com/vmware/vip/i18n/HttpRequesterTest.java
Labels: cla-not-required

#155 resolve sonar scan failure in PR, add sonar organization in -D parameter
  .travis.yml
  src/test/java/com/vmware/vip/i18n/CacheManagerTest.java
Labels: cla-not-required

#154 update the i18n configuration to fixed s3 https start failed
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v2/combine/TranslationWithPatternTest.java
  g11n-ws/vip-manager-l10n/build.gradle
Labels: cla-not-required
