Repository vmware/singleton, pull requests merged in 2019-11, with the labels that each got.

#238 Add support to shared component
  src/main/java/com/vmware/vipclient/i18n/I18nFactory.java
  src/main/java/com/vmware/vipclient/i18n/VIPCfg.java
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/exceptions/VIPClientInitException.java
  src/main/java/com/vmware/vipclient/i18n/filters/VIPComponentFilter.java
  src/main/java/com/vmware/vipclient/i18n/fmt/common/MessageSupport.java
  src/test/java/com/vmware/vip/i18n/CacheManagerTest.java
  src/test/java/com/vmware/vip/i18n/DateFormatUtilTest.java
  src/test/java/com/vmware/vip/i18n/FormatTest.java
  src/test/java/com/vmware/vip/i18n/HttpRequesterTest.java
  src/test/java/com/vmware/vip/i18n/LocaleTest.java
  src/test/java/com/vmware/vip/i18n/MessageCache2Test1.java
  src/test/java/com/vmware/vip/i18n/MessageCache2Test2.java
  src/test/java/com/vmware/vip/i18n/MessageCacheTest1.java
  src/test/java/com/vmware/vip/i18n/MessageCacheTest2.java
  src/test/java/com/vmware/vip/i18n/MessageFormatTest.java
  src/test/java/com/vmware/vip/i18n/NumberFormatUtilTest.java
  src/test/java/com/vmware/vip/i18n/PersistantCacheTest.java
  src/test/java/com/vmware/vip/i18n/PluralFormatTest.java
  src/test/java/com/vmware/vip/i18n/SharedComponentTest.java
  src/test/java/com/vmware/vip/i18n/TranslationMessage2Test.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
  src/test/java/com/vmware/vip/i18n/VIPCfgTest.java
  src/test/resources/vipconfig-child.properties
Labels: cla-not-required

#267 promote quality gate as current quality status.
  sonar/quality_gates/java-client.json
  sonar/quality_gates/service_quality_gate.json
Labels: cla-not-required

#265 fixed the scan bug
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/bundle/InitBundleListener.java
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/MultComponentDao.java
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/OneComponentDao.java
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/ProductDao.java
  g11n-ws/modules/md-restful-l10n-synch/src/main/java/com/vmware/l10n/synch/controller/TranslationCommitGitController.java
  g11n-ws/modules/md-restful-l10n-synch/src/main/java/com/vmware/l10n/synch/init/SynchInfoService.java
  g11n-ws/modules/md-restful-synch/src/main/java/com/vmware/vip/messages/synch/schedule/SynchInfoSchedule.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/utils/LocaleUtility.java
  g11n-ws/tools/tool-trans-fetcher/src/main/java/com/vmware/vip/fetcher/common/FileUtils/OrderedPropertiesUtils.java
  g11n-ws/tools/tool-trans-fetcher/src/main/java/com/vmware/vip/fetcher/common/dto/OrderedProperties.java
  g11n-ws/tools/tool-trans-fetcher/src/main/java/com/vmware/vip/fetcher/monitor/UpdateThread.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsMsg.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/LocaleUtils.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/SingleComponentServiceImpl.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/utils/HttpRequester.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/utils/RSAResourceFileUtils.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/utils/ResouceFileUtils.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/utils/RourceRSAKeyUtils.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/utils/VipRSAUtils.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/RemoteSyncServiceTest.java
Labels: cla-not-required

#261 add the multcomponent API
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductAPI.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentAPI.java
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/APIV2.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/multcomponent/MultComponentService.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/utils/LocaleUtility.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/status/APIResponseStatus.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductAPITest.java
Labels: cla-not-required

#235 Support fetching translations of multiple components in one call #219
  .gitignore
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/common/ConstantsMsg.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/BaseOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/ComponentsBasedOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/url/V2URL.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentsService.java
  src/main/java/com/vmware/vipclient/i18n/util/StringUtil.java
  src/test/java/com/vmware/vip/i18n/BaseTestClass.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
  src/test/resources/JavaclientTest/1.0.0/USER/messages_de.json
  src/test/resources/JavaclientTest/1.0.0/USER/messages_en.json
  src/test/resources/JavaclientTest/1.0.0/USER/messages_es.json
  src/test/resources/JavaclientTest/1.0.0/USER/messages_fr.json
  src/test/resources/JavaclientTest/1.0.0/USER/messages_ja.json
  src/test/resources/JavaclientTest/1.0.0/USER/messages_ko.json
  src/test/resources/JavaclientTest/1.0.0/USER/messages_latest.json
  src/test/resources/JavaclientTest/1.0.0/USER/messages_zh-Hans.json
  src/test/resources/JavaclientTest/1.0.0/USER/messages_zh-Hant.json
  src/test/resources/mockserver/__files/body-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0.json
  src/test/resources/mockserver/mappings/mapping-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0.json
Labels: cla-not-required

#269 merge saas and lite version
  g11n-ws/settings.gradle
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/l10n/translation/controller/TranslationSyncServerControllerTest.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestModels.java
  g11n-ws/vip-manager-lite-i18n/build.gradle
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/LiteBootApplication.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPICrossDomainInterceptor.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteWebConfiguration.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/ServerProperties.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/TomcatConfig.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/VIPTomcatConnectionCustomizer.java
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-pgdb.yml
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-pgdb_staging.yml
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-prod.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-staging.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-testing.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/ehcache3.xml
  g11n-ws/vip-manager-lite-i18n/src/main/resources/log4j2-spring.xml
  g11n-ws/vip-manager-lite-i18n/src/main/resources/open_source_licenses.TXT
  g11n-ws/vip-manager-lite-i18n/src/main/resources/test.jks
  g11n-ws/vip-manager-lite-i18n/src/main/resources/vip.cer
  g11n-ws/vip-manager-lite-i18n/src/main/resources/vip.csr
  g11n-ws/vip-manager-lite-i18n/src/main/resources/vip.jks
  g11n-ws/vip-manager-lite-i18n/src/main/resources/vip.key
  g11n-ws/vip-manager-lite-i18n/src/main/resources/vipauth.db
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/authentication/AuthenticationAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/authentication/KeyAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/CacheUtil.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/ConstantsForTest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/GitTranslationFetcherMainForTest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/MessageUtil.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/RequestUtil.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/ResponseUtil.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/TranslationFetcherTest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/date/DateAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/locale/LocaleAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/pattern/PatternAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationComponentAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationKeyAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationProductAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationProductComponentAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationProductComponentKeyAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationSourceAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationSyncAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v2/LocaleAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v2/formatting/pattern/FormattingPatternAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/config/ConfigurationTest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/config/SpringBootTest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/l3/LocalePickupTest.java
  g11n-ws/vip-manager-lite-i18n/src/test/resources/ehcache.xml
  g11n-ws/vip-manager-lite-i18n/src/test/resources/map.properties
Labels: cla-not-required

#277 fixed the mult-component get big size translation error
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/MultComponentDao.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/multcomponent/MultComponentService.java
Labels: cla-not-required

#282 promote unit test coverage
  sonar/quality_gates/angular-client.json
  sonar/quality_gates/java-client.json
  sonar/quality_gates/js-core-sdk.json
  sonar/quality_gates/service_quality_gate.json
Labels: cla-not-required

#281 fixed Singleton service lite build bugs
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#280 Add CHNAGELOG-0.2.0
  CHANGELOG-0.2.0.md
Labels: cla-not-required, kind/documentation

#289 add java client sample app test script, just a interface, no implementation yet.
  autotest/client/java_client_sample_app/test_sample_app.sh
Labels: cla-not-required

#290 change metirc to new code since overall code almost meet the gates.
  sonar/quality_gates/java-client.json
  sonar/quality_gates/service_quality_gate.json
Labels: cla-not-required

#287 fix scan unit test
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/utils/LocaleUtility.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestExceptions.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestModels.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestStartBoot.java
  g11n-ws/vip-manager-lite-i18n/build.gradle
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/config/ConfigurationTest.java
Labels: cla-not-required

#292 add execute permission
  autotest/client/java_client_sample_app/test_sample_app.sh
Labels: cla-not-required

#286 add multi-component version fallback
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/utils/VersionMatcher.java
Labels: cla-not-required

#295 add sanity test for java client sample app
  autotest/client/java_client_sample_app/sample_app_sanity_test.sh
  autotest/client/java_client_sample_app/test_sample_app.sh
Labels: cla-not-required

#294 G11n java client
  sample-client-app/src/main/java/com/vmware/vipclient/sample/Main.java
Labels: cla-not-required

#296 Add java client sample app sanity test in CI pipeline
  .travis.yml
Labels: cla-not-required

#298 fix typo/format issue and add sha1 for npm packages
  content/en/docs/get-started/download-and-installation.md
  content/en/docs/overview/singleton-service/configurations/enable-S3-storage.md
Labels: cla-not-required

#300 Publishing to gh-pages
  404.html
  _footer/index.html
  categories/index.html
  docs/get-started/download-and-installation/index.html
  docs/get-started/index.html
  docs/get-started/index.xml
  docs/get-started/quick-start/index.html
  docs/index.html
  docs/overview/index.html
  docs/overview/singleton-sdk/angular-client-introduction/index.html
  docs/overview/singleton-sdk/csharp-client-introduction/index.html
  docs/overview/singleton-sdk/index.html
  docs/overview/singleton-sdk/java-client-introduction/index.html
  docs/overview/singleton-sdk/javascript-client-introduction/index.html
  docs/overview/singleton-sdk/python-client-introduction/index.html
  docs/overview/singleton-service/configurations/enable-pseudo-translation/index.html
  docs/overview/singleton-service/configurations/enable-s3-storage/index.html
  docs/overview/singleton-service/configurations/enable-source-collection/index.html
  docs/overview/singleton-service/configurations/index.html
  docs/overview/singleton-service/configurations/index.xml
  docs/overview/singleton-service/index.html
  docs/overview/singleton-service/singleton-service-apis/index.html
  docs/tutorials/deploy-singleton-service-in-your-app/index.html
  docs/tutorials/index.html
  docs/tutorials/integrate-singleton-in-angular-app/index.html
  docs/tutorials/integrate-singleton-in-csharp-app/index.html
  docs/tutorials/integrate-singleton-in-java-app/index.html
  docs/tutorials/integrate-singleton-in-javascript-app/index.html
  docs/tutorials/integrate-singleton-in-python-app/index.html
  index.html
  index.xml
  tags/index.html
Labels: cla-not-required

#301 [BUG] [Singleton Service] new category "dateFields" (relative pattern data) doesn't support in combination API
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationWithPatternAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/utils/CommonUtility.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v1/formatting/pattern/FormattingPatternAPI.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/formatting/pattern/FormattingPatternAPI.java
Labels: cla-not-required

#304 stop build CI pipeline if only docs updates
  .travis.yml
Labels: cla-not-required

#305 stop build ci pipeline for only docs updates
  .travis.yml
Labels: cla-not-required

#309 remove commit range changing
  .travis.yml
Labels: cla-not-required

#308 Stop build CI pipeline for only docs update
  .travis.yml
Labels: cla-not-required

#310 Skip sonar quality check for only travis.yml updates
  .travis.yml
Labels: cla-not-required

#306 stop build ci pipeline for only docs updates
  .travis.yml
Labels: area/js-client, cla-not-required
