Repository vmware/singleton, pull requests merged in 2019-09, with the labels that each got.

#156 The build failed to start when disable swagger-ui
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/SwaggerConfig.java
Labels: cla-not-required

#161 filter out the file from component list and local list
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3OneComponentDaoImpl.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3ProductDaoImpl.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/util/S3Utils.java
Labels: cla-not-required

#153 change angular-client package name
  README.md
  package-lock.json
  package.json
  sample/README.md
  sample/package.json
  sample/src/app/app.component.ts
  sample/src/app/app.module.ts
  sample/src/app/modules/i18n/i18n-service/i18n-service.component.ts
  sample/src/app/modules/i18n/i18n.module.ts
  sample/src/app/modules/l10n/l10n-pipe/l10n-pipe.component.ts
  sample/src/app/modules/l10n/l10n-service/l10n-service.component.ts
  sample/src/app/modules/l10n/l10n.module.ts
  sample/src/app/modules/l10n/l10n/l10n.component.ts
  sample/src/app/modules/lazy-module/lazy.module.ts
  sample/src/app/modules/vip-header/header/header.component.ts
  sample/src/app/modules/vip-header/i18n.util.ts
  sample/src/app/modules/vip-header/vip-header.module.ts
Labels: cla-not-required

#171 https://github.com/vmware/singleton/issues/102 Etag in the response h…
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/status/Response.java
Labels: cla-not-required

#157 Upgrade gradle to version 5.6.1
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/test/resources/level2/en/patterns.json
Labels: area/java-client, cla-not-required, java

#176 Add test cases for java client customize header
  autotest/client/java/build.gradle
  autotest/client/java/pom.xml
  autotest/client/java/resource/testng.xml
  autotest/client/java/src/com/vmware/vip/test/javaclient/TestBase.java
  autotest/client/java/src/com/vmware/vip/test/javaclient/httprequester/CustomizeHeader.java
Labels: cla-not-required

#144 Add version fallback
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/ProductDao.java
  g11n-ws/modules/md-data-api-pgimpl/src/main/java/com/vmware/vip/messages/data/dao/pgimpl/PgProductApiImpl.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3ProductDaoImpl.java
  g11n-ws/modules/md-data-api/src/main/java/com/vmware/vip/messages/data/dao/api/IProductDao.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentAction.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/product/IProductService.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/product/ProductService.java
Labels: cla-not-required

#178 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla-not-required

#179 Update the swagger-ui url in README
  README.md
Labels: cla-not-required

#119 Replace superagent with axios.
  cli/collect-source-bundle.js
  cli/generate-token.js
  cli/load-i18n-package.js
  cli/translation-service.js
  cli/vip.js
  package.client.json
  package.json
  samples/server/express/package-lock.json
  samples/server/express/package.json
Labels: area/js-client, cla-not-required

#181 change stage name to more precise one
  .travis.yml
Labels: cla-not-required

#182 change stage name to more precise one
  .travis.yml
Labels: cla-not-required

#185 Correct some format errors in README.md
  README.md
Labels: cla-not-required

#186 js-client： readme, client version, js sample
  README.md
  package.client.json
  samples/client/js/README.md
  samples/client/js/package-lock.json
  samples/client/js/package.json
Labels: cla-not-required

#187 Add 'setDefaultLocale' API and enable some other features.
  .gitignore
  .npmignore
  README.md
  package-lock.json
  package.json
  sample/package-lock.json
  sample/src/app/app.module.ts
  sample/src/app/modules/lazy-module/contact.l10n.ts
  sample/src/app/modules/lazy-module/lazy.module.ts
  sample/src/app/modules/vip-header/header.l10n.ts
  sample/src/app/modules/vip-header/i18n.util.ts
  src/constants.ts
  src/loader.ts
  src/services/i18n.service.ts
  src/services/l10n.service.ts
  src/services/locale.service.ts
  src/services/vip.service.ts
  webpack.config.js
Labels: cla-not-required

#188 Correct l10n data attribute naming.
  samples/client/js/html/example.html
  samples/client/js/src/config.js
Labels: cla-not-required

#180 Sort strings in translation bundle in alphabet
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/OneComponentDao.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/SortJSONUtils.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/SourceDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/impl/SingleComponentDaoImpl.java
Labels: cla-not-required

#193 [Singleton Service][Get pattern by language&region] plurals rule should always follow with language
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/pattern/PatternServiceImpl.java
Labels: cla-not-required

#184 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-not-required

#192 Improve LocaleUtility
  src/main/java/com/vmware/vipclient/i18n/util/LocaleUtility.java
  src/test/java/com/vmware/vip/i18n/LocaleTest.java
Labels: cla-not-required

#200 update the script to remove the sample bundle file in builder
  g11n-ws/vip-manager-i18n/build.gradle
Labels: cla-not-required

#201 update the S3 configuration file item
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#204 upgrade dependency libs
  g11n-ws/build.gradle
  g11n-ws/modules/md-restful-api-db/build.gradle
  g11n-ws/modules/md-service-authen/build.gradle
Labels: cla-not-required

#209 [Angular] Update package.json
  package.json
  sample/package-lock.json
Labels: cla-not-required
