Repository vmware/singleton, pull requests merged in 2020-08, with the labels that each got.

#693 Add create timezone name list feature data
  g11n-ws/tools/tool-cldr-extractor/build.gradle
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/PatternParseMain.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/PatternUtil.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/common/CLDRConstants.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/common/Constants.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/pattern/action/PatternAction.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/pattern/service/IPatternService.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/pattern/service/impl/PatternServiceImpl.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/CLDRUtils.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/timezone/CldrMetaZone.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/timezone/CldrTimeZoneUtils.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/timezone/TimeZoneDisplayName.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/timezone/TimeZoneName.java
  g11n-ws/tools/tool-cldr-extractor/src/test/java/com/vmware/i18n/PatternUtilTest.java
  g11n-ws/tools/tool-cldr-extractor/src/test/java/com/vmware/test/i18n/I18nUtilTest.java
Labels: cla-not-required

#702 Fix issue 700 for unittest on python 2
  sgtn4python/sgtn_util.py
  sgtn4python/test/simulate.json
  sgtn4python/test/test_properties_parser.py
  sgtn4python/test/test_sgtn_client.py
  sgtn4python/test/test_sgtn_util.py
Labels: cla-not-required

#696 Fix bug https://github.com/vmware/singleton/issues/692
  bundle_dao.go
  bundle_test.go
  cache_info.go
  cache_service.go
  cache_test.go
  common.go
  config.go
  config_test.go
  consts.go
  data_default.go
  data_service.go
  data_test.go
  go.mod
  go.sum
  httpclient_test.go
  inst.go
  inst_test.go
  logger_test.go
  messages.go
  server_dao.go
  server_test.go
  testdata/mock/mappings/componentMessages.json
  testutil_test.go
  translation.go
  translation_manager.go
  translation_test.go
Labels: cla-not-required

#698 Add introduction document of singleton python client sdk
  content/en/docs/overview/singleton-sdk/python-client-introduction.md
Labels: cla-not-required

#705 Bug https://github.com/vmware/singleton/issues/694
  .travis.yml
  cache_service.go
  config.go
  go.sum
  inst.go
  messages.go
  server_dao.go
  server_test.go
  testdata/mock/__files/componentMessages-versionfallback.json
  testdata/mock/mappings/componentMessages.json
  translation.go
  translation_manager.go
Labels: cla-not-required

#706 fixed l10n manager bugs 671 and 697
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/status/APIResponseStatus.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CspAuthInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/WebConfiguration.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/SourceUtils.java
Labels: cla-not-required

#713 Getting from service when source is unavailable
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
Labels: cla-not-required

#714 remove invalid test case
  autotest/client/java/src/com/vmware/vip/test/javaclient/level2/CurrencyTest.java
  autotest/client/java_client_sample_app/sample_app_sanity_test.sh
Labels: area/ci, area/test-automation, cla-not-required

#716 Update 0.4 Changelog
  CHANGELOG-0.4.md
Labels: cla-not-required

#699 G11n java client - Fix for expiration-related issues (issues 604, 664, and 662)
  src/main/java/com/vmware/vipclient/i18n/base/cache/MessageCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalMessagesOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/ComponentBasedOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/ComponentsBasedOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/CacheService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentsService.java
  src/main/java/com/vmware/vipclient/i18n/util/LocaleUtility.java
  src/test/java/com/vmware/vip/i18n/MessageCacheTest1.java
  src/test/java/com/vmware/vipclient/i18n/messages/service/CacheServiceTest.java
Labels: cla-not-required

#720 Create python-client.json for sonar quality gate of g11n-python-client CI
  sonar/quality_gates/python-client.json
Labels: cla-not-required

#721 Create .travis.yml to add g11n-python-client CI
  .travis.yml
Labels: area/ci, cla-not-required

#723 allow register product name bug
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/ProductDao.java
  g11n-ws/modules/md-data-api-pgimpl/src/main/java/com/vmware/vip/messages/data/dao/pgimpl/PgProductApiImpl.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3ProductDaoImpl.java
  g11n-ws/modules/md-data-api/src/main/java/com/vmware/vip/messages/data/dao/api/IProductDao.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/product/IProductService.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/product/ProductService.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/Interceptor/APIValidationInterceptor.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/WebConfiguration.java
Labels: cla-not-required

#727 Fix issue 726: 'error on windows' by using '/' in path and correspond…
  sgtn4python/sgtn_client.py
  sgtn4python/sgtn_util.py
  sgtn4python/test/test_sgtn_util.py
Labels: cla-not-required

#728 G11n java client - fix for bug on getting offline component list in jar file
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalComponentOpt.java
Labels: cla-not-required

#736 Add test of sample app with shared lib into java client CI
  autotest/client/java_client_sample_app/sample_app_sanity_test.sh
Labels: area/ci, cla-not-required

#722 Copyright year auto increase
  check_headers.py
Labels: area/ci, cla-not-required

#743 update testng classpath
  .travis.yml
Labels: area/ci, cla-not-required

#735 G11n java client - Sample application with shared library
  sample-client-app/sample-app-with-shared-lib/.gitignore
  sample-client-app/sample-app-with-shared-lib/README.md
  sample-client-app/sample-app-with-shared-lib/build.gradle
  sample-client-app/sample-app-with-shared-lib/src/main/java/com/vmware/vipclient/sample/Main.java
  sample-client-app/sample-app-with-shared-lib/src/main/java/com/vmware/vipclient/sample/SharedLibDemo.java
  sample-client-app/sample-app-with-shared-lib/src/main/resources/log4j.properties
  sample-client-app/sample-app-with-shared-lib/src/main/resources/offlineBundles/default/messages_fr.json
  sample-client-app/sample-app-with-shared-lib/src/main/resources/sampleconfig.properties
  sample-client-app/sample-app-with-shared-lib/src/main/resources/sharedlibrary.properties
  sample-client-app/sample-shared-library/.gitignore
  sample-client-app/sample-shared-library/README.md
  sample-client-app/sample-shared-library/build.gradle
  sample-client-app/sample-shared-library/src/main/java/com/vmware/vipclient/sample/shared/Shared.java
  sample-client-app/sample-shared-library/src/main/resources/offlineBundles/shared/messages_en.json
  sample-client-app/sample-shared-library/src/main/resources/offlineBundles/shared/messages_es.json
  sample-client-app/sample-shared-library/src/main/resources/sharedlib.properties
Labels: cla-not-required

#745 describe how to add copyright and license
  CONTRIBUTING.md
Labels: cla-not-required, kind/documentation

#741 Compress Singleton Service responses to improve UI performance
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/Interceptor/EtagHeaderFilter.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/TomcatConfig.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/VIPTomcatConnectionCustomizer.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/WebConfiguration.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#752 fixed the Config file copyright files
  g11n-ws/modules/md-data-initdb/src/main/resources/application-db_dev.yml
  g11n-ws/modules/md-data-initdb/src/main/resources/application.yml
  g11n-ws/modules/md-data-initdb/src/main/resources/scripts/__init__.py
  g11n-ws/modules/md-data-initdb/src/main/resources/scripts/pseudodb.py
  g11n-ws/modules/md-service-i18n-l3/src/main/resources/map.properties
  g11n-ws/scripts/singletonall.sh
  g11n-ws/scripts/singletoncheck.sh
  g11n-ws/scripts/singletonstart.sh
  g11n-ws/scripts/singletonstop.sh
  g11n-ws/tools/tool-cldr-extractor/build.gradle
  g11n-ws/tools/tool-cldr-extractor/settings.gradle
  g11n-ws/tools/tool-cldr-extractor/src/main/resources/config.properties
  g11n-ws/tools/tool-trans-fetcher/build.gradle
  g11n-ws/tools/tool-trans-fetcher/src/main/resources/config.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application.properties
  g11n-ws/vip-manager-i18n/src/test/resources/map.properties
  g11n-ws/vip-manager-l10n-agent/src/main/resources/application.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application.properties
  g11n-ws/vip-manager-lite-i18n/src/test/resources/map.properties
Labels: cla-not-required
