Repository vmware/singleton, pull requests merged in 2020-09, with the labels that each got.

#753 G11n java client - Fix for issue#746 - MsgOriginsQueue cannot be cleared once initializing VIPCfg
  src/main/java/com/vmware/vipclient/i18n/VIPCfg.java
Labels: cla-not-required

#738 [g11n-java-client] Fix for issue #717 - non-supported locales trigger a request to VIP service in a separate thread for every getMessage/getMessages request
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
  src/test/java/com/vmware/vipclient/i18n/messages/service/OfflineModeTest.java
Labels: cla-not-required

#756 [g11n-java-client] code clean up
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
Labels: cla-not-required

#760 Compress Singleton Service responses to improve UI performance
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteWebConfiguration.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/TomcatConfig.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/VIPTomcatConnectionCustomizer.java
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#762 update CI yaml for new bundle location
  .travis.yml
Labels: area/test-automation, cla-not-required

#766 [CI] use travis build matrix to test in parallel
  .travis.yml
Labels: area/ci, cla-not-required

#769 use travis build matrix to test in parallel
  .travis.yml
Labels: area/ci, cla-not-required

#768 use travis build matrix to test in parallel
  .travis.yml
Labels: area/ci, cla-not-required

#775 use travis build matrix to test in parallel
  .travis.yml
Labels: area/ci, cla-not-required

#776 use travis build matrix to test in parallel
  .travis.yml
Labels: area/ci, cla-not-required

#777 use travis build matrix to test in parallel
  .travis.yml
Labels: area/ci, cla-not-required

#767 use travis build matrix to test in parallel
  .travis.yml
Labels: area/ci, cla-not-required

#765 fixed the timezone fallback format data
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/timezone/CldrTimeZoneUtils.java
Labels: cla-not-required

#780 Fix issue #771 [Tech Debt] Fix 24 bugs in master branch found by Sonar Cloud scan
  g11n-ws/modules/md-data-api-pgimpl/src/main/java/com/vmware/vip/messages/data/dao/pgimpl/operate/impl/DocOperateImpl.java
  g11n-ws/modules/md-data-api-pgimpl/src/main/java/com/vmware/vip/messages/data/dao/pgimpl/operate/impl/StrOperateImpl.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/csp/service/TokenService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/TokenService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/SourceDaoImpl.java
Labels: cla-not-required

#792 Add a customized controller to handle invalid request
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/CustomErrorController.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/CustomErrorController.java
Labels: cla-not-required

#791 update to let unittest run correctly on Windows 10 of English Language
  singletonclient/SingletonIcu/SingletonUtility.cpp
  singletonclient/UnitTestSingleton/BaseIo.cs
  singletonclient/UnitTestSingleton/TestClient.cs
  singletonclient/UnitTestSingleton/testdata/TestSource.properties
  singletonclient/UnitTestSingletonIcu/TestDateTime.cs
  singletonclient/UnitTestSingletonIcu/TestPlural.cs
Labels: cla-not-required

#782 Fix for bug 781 - ComponentService.getMessages is not retrieving "matchedLocale" from cache properly
  src/main/java/com/vmware/vipclient/i18n/base/cache/MessageCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/CacheService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentsService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ProductService.java
  src/test/java/com/vmware/vip/i18n/HttpRequesterTest.java
  src/test/java/com/vmware/vip/i18n/LocaleTest.java
  src/test/java/com/vmware/vipclient/i18n/messages/service/OfflineModeTest.java
Labels: cla-not-required

#801 include ci update from g11n-java-client branch
  .travis.yml
Labels: area/ci, cla-not-required

#800 update the timezone name list data format
  g11n-ws/tools/tool-cldr-extractor/build.gradle
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/common/Constants.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/pattern/service/impl/PatternServiceImpl.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/timezone/CldrMetaZone.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/timezone/CldrTimeZoneUtils.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/timezone/TimeZoneName.java
  g11n-ws/tools/tool-cldr-extractor/src/test/java/com/vmware/i18n/PatternUtilTest.java
Labels: cla-not-required

#797 Fix issues found after upgrading sonar jdk to 11
  build.gradle
  src/test/java/com/vmware/vip/i18n/BaseTestClass.java
  src/test/java/com/vmware/vip/i18n/LocaleTest.java
  src/test/java/com/vmware/vip/i18n/MessageCacheTest1.java
  src/test/java/com/vmware/vip/i18n/PersistantCacheTest.java
  src/test/java/com/vmware/vip/i18n/TranslationMessage2Test.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
  src/test/java/com/vmware/vipclient/i18n/messages/service/CacheServiceTest.java
Labels: cla-not-required

#804 Customized Date time support
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/CLDRUtils.java
  g11n-ws/tools/tool-cldr-extractor/src/main/resources/config.properties
Labels: cla-not-required

#798 Fix sonar errors upgrading sonar JDK to 11
  build.gradle
  src/test/java/com/vmware/vip/i18n/BaseTestClass.java
  src/test/java/com/vmware/vip/i18n/LocaleTest.java
  src/test/java/com/vmware/vip/i18n/MessageCacheTest1.java
  src/test/java/com/vmware/vip/i18n/PersistantCacheTest.java
  src/test/java/com/vmware/vip/i18n/TranslationMessage2Test.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
Labels: cla-not-required

#805 G11n java client - Caching the list of supported locales used by L3 to enhance performance
  src/main/java/com/vmware/vipclient/i18n/base/cache/MessageCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/ProductOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalLocaleOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalMessagesOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalProductOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/RemoteProductOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/dto/MessagesDTO.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/CacheService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ProductService.java
  src/test/java/com/vmware/vip/i18n/SharedComponentTest.java
Labels: cla-not-required

#803 Fix issues found after sonar upgrading jdk to 11
  .travis.yml
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/product/ProductService.java
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/RequestUtil.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/ResponseUtil.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v2/LocaleAPITest.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/config/SwaggerConfigTest.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/config/TestInterceptor.java
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/SourceSendingCronTest.java
  g11n-ws/vip-manager-lite-i18n/build.gradle
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPICacheControlInterceptor.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteCustomErrorController.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteServerProperties.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteTomcatConfig.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteTomcatConnectionCustomizer.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteWebConfiguration.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/RequestUtil.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/ResponseUtil.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v2/LocaleAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/config/ConfigurationTest.java
Labels: cla-not-required

#809 Delete unused classes
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/CLDRUtils.java
Labels: cla-not-required
