Repository vmware/singleton, pull requests merged in 2020-11, with the labels that each got.

#852 remove the l10n locale list match validate
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/WebConfiguration.java
  g11n-ws/vip-manager-l10n/src/main/resources/application.properties
Labels: cla-not-required

#848 Code clean up in VIPCfg. Remove TranslationCacheManager member from VIPCfg because TranslationCacheManager is using Singleton design pattern.
  src/main/java/com/vmware/vipclient/i18n/VIPCfg.java
  src/main/java/com/vmware/vipclient/i18n/base/Task.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/TranslationCacheManager.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/persist/CacheSyncThread.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/persist/CacheSyncThreadPool.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/persist/DiskCacheLoader.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/CacheService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/FormattingCacheService.java
Labels: cla-not-required

#855 Fix for 839: Do not use locale fallback when getting source locale messages and collectedSourceMsg in TranlationMessage.getMessage
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/ComponentBasedOpt.java
  src/test/resources/mockserver/__files/body-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0-locales-en-components-JAVA-pseudo-true.json
  src/test/resources/mockserver/mappings/mapping-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0-locales-en-components-JAVA-pseudo-true.json
Labels: area/java-client, cla-not-required, kind/bug, priority/medium

#866 fix print client header bug
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/Interceptor/APIValidationInterceptor.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPIValidationInterceptor.java
Labels: cla-not-required

#859 Code clean up: unifying cache expire logic in CacheItem; deprecating old expire methods
  src/main/java/com/vmware/vipclient/i18n/base/cache/Cache.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/CacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/FormatCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/FormattingCache.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/LocaleCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/MessageCache.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/MessageCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/PatternCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/TranslationCacheManager.java
Labels: area/java-client, cla-not-required, kind/enhancement, priority/low

#872 change the l10n resource collection url to gateway pattern
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/l10n/L10nI18nAPI.java
Labels: cla-not-required

#884 fix l10n interceptor path pattern issue
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/WebConfiguration.java
Labels: cla-not-required

#875 change java client dependent pattern lib version to fix App-check failure
  build.gradle
Labels: area/java-client, cla-not-required

#887 add the s3 configuration of encrypt access key and secret key
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/RsaCryptUtils.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/S3Config.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#853 fix issue 674 to make properties parser correct.
  singletonclient/SingletonClient/Implementation/Support/SingletonParserProperties.cs
Labels: cla-not-required

#879 fix bug #819: [BUG] [Service] [getPattern] Week info("firstDayOfWeek" &"weekendOfRange") should also follow CLDR data
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/common/Constants.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/common/DayEnum.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/CLDRUtils.java
  g11n-ws/tools/tool-cldr-extractor/src/main/java/com/vmware/i18n/utils/LocaleDataUtils.java
Labels: cla-not-required
