Repository vmware/singleton, pull requests merged in 2020-10, with the labels that each got.

#818 Update .travis.yml to upgrade sonar jdk to 11 for java client 0.4.2 CI
  .travis.yml
Labels: area/ci, cla-not-required

#817 Update .travis.yml to upgrade sonar jdk to 11 for java client CI
  .travis.yml
Labels: area/ci, cla-not-required

#826 code clean up in ComopnentBasedOpt - initialize props at instantiation
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/ComponentBasedOpt.java
Labels: cla-not-required

#825 code clean up - remove unused code from LocaleUtility.java, rename methods in ProductService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ProductService.java
  src/main/java/com/vmware/vipclient/i18n/util/LocaleUtility.java
Labels: area/java-client, kind/enhancement, priority/low

#813 Fix for bug 812 G11n-java-client New workflow's Translation.getMessage must be able to use latest source messages from VIP service
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
  src/test/java/com/vmware/vip/i18n/HttpRequesterTest.java
Labels: cla-not-required, priority/high

#820 support code 604 in case of version fallback
  singletonclient/SingletonClient/Implementation/SingletonUtil.cs
Labels: cla-not-required

#822 support code 604 in case of version fallback
  sgtn4python/sgtn_client.py
Labels: cla-not-required

#828 Upgrade dependencies to latest version
  build.gradle
Labels: cla-not-required

#832 get project domain in a different way and check null pointer
  singletonclient/SingletonClient/Implementation/SingletonConfig.cs
  singletonclient/SingletonClient/Implementation/SingletonRelease.cs
  singletonclient/SingletonClient/Implementation/SingletonUtil.cs
Labels: cla-not-required

#810 add Request ID in log
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/Interceptor/APIValidationInterceptor.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/WebConfiguration.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPIValidationInterceptor.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteWebConfiguration.java
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#816 Merge from 4.0.2 branch
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/l2/plural/parser/PluralRules.java
  src/main/java/com/vmware/vipclient/i18n/util/FormatUtils.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
Labels: cla-not-required

#835 inconsistent response code when token validation failed in i18n and l10n
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/auth/interceptor/AuthInterceptor.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsKeys.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CspAuthInterceptor.java
Labels: cla-not-required

#836 upgrade spring jars
  g11n-ws/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#838 Merge402
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
Labels: cla-not-required

#837 Revert upgrading dependencies
  build.gradle
Labels: cla-not-required

#834 Issue 833- Optimize VIPService by removing unused code. Automate initialization of VIPService in VIPCfg
  src/main/java/com/vmware/vipclient/i18n/VIPCfg.java
  src/main/java/com/vmware/vipclient/i18n/base/HttpRequester.java
  src/main/java/com/vmware/vipclient/i18n/base/VIPService.java
Labels: cla-not-required

#829 G11n java client - code cleanup - removing null checks for properties/variables that will never be null
  src/main/java/com/vmware/vipclient/i18n/base/cache/MessageCacheItem.java
Labels: area/java-client, cla-not-required, kind/enhancement, priority/low

#830 G11n java client - vipcfg cleanup
  src/main/java/com/vmware/vipclient/i18n/VIPCfg.java
Labels: area/java-client, cla-not-required, kind/enhancement, priority/low

#823 G11n java client [BUG 754] Performance impact on the very first L3 fetch for a non-supported locale
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ProductService.java
  src/main/java/com/vmware/vipclient/i18n/util/LocaleUtility.java
  src/test/java/com/vmware/vip/i18n/HttpRequesterTest.java
  src/test/java/com/vmware/vip/i18n/LocaleTest.java
  src/test/resources/mockserver/mappings/mapping-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0-locales-zh-Hans-components-JAVA-zNUip.json
Labels: cla-not-required, kind/bug, priority/medium

#844 Recorrect change from merging 402 branch
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
Labels: cla-not-required

#846 change l10n response key from "status" to "response"
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/SourceController.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dto/SourceAPIResponseDTO.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/SourceUtils.java
Labels: cla-not-required

#742 add L2 cache expire logic
  src/main/java/com/vmware/vipclient/i18n/base/cache/CacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/FormatCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/LocaleCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/PatternCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/common/ConstantsMsg.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/LocaleOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/PatternOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalLocaleOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalPatternOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/RemoteL2BaseOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/RemoteLocaleOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/RemotePatternOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/FormattingCacheService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/LocaleService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/PatternService.java
  src/main/java/com/vmware/vipclient/i18n/util/ConstantsKeys.java
Labels: area/java-client

#850 clean up in TranslationMessage-use getCfg method instead of this.cfg, use this.getCfg instead of VIPCfg.getInstance
  src/main/java/com/vmware/vipclient/i18n/I18nFactory.java
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
Labels: cla-not-required, kind/enhancement, priority/low
