Repository vmware/singleton, pull requests merged in 2020-06, with the labels that each got.

#584 upgrade the singleton server dependency jars
  g11n-ws/build.gradle
  g11n-ws/modules/md-restful-api-i18n/build.gradle
  g11n-ws/modules/md-service-authen/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#590 add the configure server header buffer size feature
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/ServerProperties.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/TomcatConfig.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/VIPTomcatConnectionCustomizer.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/ServerProperties.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/TomcatConfig.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/VIPTomcatConnectionCustomizer.java
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#592 update Go client test due to some methods are changed
  autotest/client/go/goclienttest/CongfigAPI_test1.go
  autotest/client/go/goclienttest/GetConfig_test1.go
  autotest/client/go/goclienttest/InstanceAPI_test.go
  autotest/client/go/goclienttest/InstanceAPI_test1.go
  autotest/client/go/goclienttest/LocalBundlesOnly/config.json
  autotest/client/go/goclienttest/LocalBundlesOnly/getComponentList_test.go
  autotest/client/go/goclienttest/LocalBundlesOnly/getComponentTranslation_test.go
  autotest/client/go/goclienttest/LocalBundlesOnly/getLocaleList_test.go
  autotest/client/go/goclienttest/LocalBundlesOnly/getStringTranslation_test.go
  autotest/client/go/goclienttest/ServerOnly/configServerOnly.json
  autotest/client/go/goclienttest/ServerOnly/getComponentList_test.go
  autotest/client/go/goclienttest/ServerOnly/getComponentTranslation_test.go
  autotest/client/go/goclienttest/ServerOnly/getLocaleList_test.go
  autotest/client/go/goclienttest/ServerOnly/getStringTranslation_test.go
  autotest/client/go/goclienttest/cachetest/cacheManagementExternal_test.go
  autotest/client/go/goclienttest/cachetest/cacheManagementExternal_test1.go
  autotest/client/go/goclienttest/cachetest/cacheManagement_test.go
  autotest/client/go/goclienttest/cachetest/configCacheInitalLocalBundles.json
  autotest/client/go/goclienttest/cachetest/configCacheInitalServiceExpired.json
  autotest/client/go/goclienttest/go.mod
  autotest/client/go/goclienttest/go.sum
  autotest/client/go/goclienttest/testdata/Config/config.json
  autotest/client/go/goclienttest/testdata/Config/configDefaultLocaleEmpty.json
  autotest/client/go/goclienttest/testdata/Config/configDefaultLocaleList.json
  autotest/client/go/goclienttest/testdata/Config/configLocalBundlePathEmpty.json
  autotest/client/go/goclienttest/testdata/Config/configLocalBundlePathNonASCII.json
  autotest/client/go/goclienttest/testdata/Config/configServerEmpty.json
Labels: cla-not-required

#594 update the URL of go test accesses singleton service to http without authority
  autotest/client/go/goclienttest/ServerOnly/configServerOnly.json
  autotest/client/go/goclienttest/cachetest/configCacheInitalServiceExpired.json
  autotest/client/go/goclienttest/testdata/Config/config.json
  autotest/client/go/goclienttest/testdata/Config/configDefaultLocaleEmpty.json
  autotest/client/go/goclienttest/testdata/Config/configDefaultLocaleList.json
  autotest/client/go/goclienttest/testdata/Config/configLocalBundlePathEmpty.json
  autotest/client/go/goclienttest/testdata/Config/configLocalBundlePathNonASCII.json
Labels: cla-not-required

#566 Microsoft Translator API Regional Source Support
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/MTConfig.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/MTConfigContent.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/azure/AzureTranslatingProcessor.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
Labels: area/service

#596 Update .travis.yml to add smoke test job for go client CI
  .travis.yml
Labels: cla-not-required

#608 Add jsClient tutorials
  content/en/docs/overview/singleton-sdk/javascript-client-introduction.md
  content/en/docs/tutorials/integrate-singleton-in-javascript-app.md
Labels: cla-not-required

#609 Add jsClient tutorials
  404.html
  _footer/index.html
  categories/index.html
  docs/get-started/download-and-installation/index.html
  docs/get-started/index.html
  docs/get-started/quick-start/index.html
  docs/index.html
  docs/overview/index.html
  docs/overview/singleton-sdk/angular-client-introduction/command-line-utils/index.html
  docs/overview/singleton-sdk/angular-client-introduction/currency-format-pipe/index.html
  docs/overview/singleton-sdk/angular-client-introduction/data-initialization/index.html
  docs/overview/singleton-sdk/angular-client-introduction/date-time-format-pipe/index.html
  docs/overview/singleton-sdk/angular-client-introduction/i18n-service/index.html
  docs/overview/singleton-sdk/angular-client-introduction/index.html
  docs/overview/singleton-sdk/angular-client-introduction/isolated-feature-module/index.html
  docs/overview/singleton-sdk/angular-client-introduction/l10n-service/index.html
  docs/overview/singleton-sdk/angular-client-introduction/lazy-load-module/index.html
  docs/overview/singleton-sdk/angular-client-introduction/locale-management/index.html
  docs/overview/singleton-sdk/angular-client-introduction/localized-component-mixin/index.html
  docs/overview/singleton-sdk/angular-client-introduction/number-format-pipe/index.html
  docs/overview/singleton-sdk/angular-client-introduction/percent-format-pipe/index.html
  docs/overview/singleton-sdk/angular-client-introduction/plural-format/index.html
  docs/overview/singleton-sdk/angular-client-introduction/relative-time-format/index.html
  docs/overview/singleton-sdk/angular-client-introduction/standalone-mode/index.html
  docs/overview/singleton-sdk/angular-client-introduction/translate-directive/index.html
  docs/overview/singleton-sdk/angular-client-introduction/translate-pipe/index.html
  docs/overview/singleton-sdk/csharp-client-introduction/index.html
  docs/overview/singleton-sdk/go-client-introduction/index.html
  docs/overview/singleton-sdk/index.html
  docs/overview/singleton-sdk/java-client-introduction/index.html
  docs/overview/singleton-sdk/javascript-client-introduction/index.html
  docs/overview/singleton-sdk/python-client-introduction/index.html
  docs/overview/singleton-service/configurations/enable-new-product/index.html
  docs/overview/singleton-service/configurations/enable-product-white-list/index.html
  docs/overview/singleton-service/configurations/enable-pseudo-translation/index.html
  docs/overview/singleton-service/configurations/enable-s3-storage/index.html
  docs/overview/singleton-service/configurations/enable-source-collection/index.html
  docs/overview/singleton-service/configurations/index.html
  docs/overview/singleton-service/index.html
  docs/overview/singleton-service/singleton-service-apis/index.html
  docs/overview/singleton-service/singleton-service-script/index.html
  docs/tutorials/deploy-singleton-service-in-your-app/index.html
  docs/tutorials/index.html
  docs/tutorials/index.xml
  docs/tutorials/integrate-singleton-in-angular-app/index.html
  docs/tutorials/integrate-singleton-in-csharp-app/index.html
  docs/tutorials/integrate-singleton-in-java-app/index.html
  docs/tutorials/integrate-singleton-in-javascript-app/index.html
  docs/tutorials/integrate-singleton-in-python-app/index.html
  index.html
  index.xml
  tags/index.html
Labels: cla-not-required

#611 upgrade jar for guava and log2j2
  g11n-ws/build.gradle
  g11n-ws/modules/md-data-api-pgimpl/build.gradle
  g11n-ws/modules/md-restful-l10n-synch/build.gradle
  g11n-ws/modules/md-restful-synch/build.gradle
  g11n-ws/modules/md-service-authen/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#603 Check in L2 lib code
  .gitignore
  .npmignore
  README.MD
  config/helpers.js
  index.ts
  jest.config.json
  package.json
  src/configuration.ts
  src/data/locale_en.ts
  src/exceptions.ts
  src/formatters/date.formatter.ts
  src/formatters/number.formatter.ts
  src/formatters/plural/plural.formatter.ts
  src/formatters/plural/plurals.func.ts
  src/intl/intl.ts
  src/intl/intl.util.ts
  src/util.ts
  test/datetime.format.spec.ts
  test/locale_de.ts
  test/number.format.spec.ts
  tsconfig.json
  tslint.json
  webpack.config.js
Labels: area/js-sdk, cla-not-required

#612 change expect the value of ja in GetStringResxFile.cs and delete icu …
  autotest/client/csharp/CSharp/CSharp.csproj
  autotest/client/csharp/CSharp/Function_test/Machine_translation/GetStringMT.cs
Labels: cla-not-required

#619 smoke test for common library(g11n-js-sdk)
  autotest/client/commonlib/.gitignore
  autotest/client/commonlib/data/currencydata.xlsx
  autotest/client/commonlib/data/datedata.xlsx
  autotest/client/commonlib/data/numberdata.xlsx
  autotest/client/commonlib/data/percentdata.xlsx
  autotest/client/commonlib/data/pluraldata.xlsx
  autotest/client/commonlib/data/translationdata.xlsx
  autotest/client/commonlib/jest.config.js
  autotest/client/commonlib/karma.conf.js
  autotest/client/commonlib/package-lock.json
  autotest/client/commonlib/package.json
  autotest/client/commonlib/readme.txt
  autotest/client/commonlib/resources/patterndata_abc.ts
  autotest/client/commonlib/resources/patterndata_ar.ts
  autotest/client/commonlib/resources/patterndata_ca-ES-VALENCIA.ts
  autotest/client/commonlib/resources/patterndata_de.ts
  autotest/client/commonlib/resources/patterndata_en-001.ts
  autotest/client/commonlib/resources/patterndata_en-US.ts
  autotest/client/commonlib/resources/patterndata_en.ts
  autotest/client/commonlib/resources/patterndata_es.ts
  autotest/client/commonlib/resources/patterndata_fr-CA.ts
  autotest/client/commonlib/resources/patterndata_fr.ts
  autotest/client/commonlib/resources/patterndata_ja.ts
  autotest/client/commonlib/resources/patterndata_ko.ts
  autotest/client/commonlib/resources/patterndata_zh-Hans.ts
  autotest/client/commonlib/resources/patterndata_zh-TW.ts
  autotest/client/commonlib/test/currency.spec.ts
  autotest/client/commonlib/test/date.spec.ts
  autotest/client/commonlib/test/number.spec.ts
  autotest/client/commonlib/test/percent.spec.ts
  autotest/client/commonlib/test/plural.spec.ts
  autotest/client/commonlib/tsconfig.json
  autotest/client/commonlib/useful/es-MX-US.json
  autotest/client/commonlib/useful/es-US(es-US).json
  autotest/client/commonlib/useful/pt-BR(pt).json
  autotest/client/commonlib/useful/pt-PT(pt-PT).json
  autotest/client/commonlib/useful/pt-PT-BR.json
  autotest/client/commonlib/useful/wiremock/mappings/tovip.json
  autotest/client/commonlib/useful/wiremock/startmock.bat
  autotest/client/commonlib/utils/commonactions.ts
  autotest/client/commonlib/utils/constants.ts
  autotest/client/commonlib/utils/excelreader.ts
  autotest/client/commonlib/utils/stringutil.ts
Labels: cla-not-required

#624 Support named arguments to format message
  src/main/java/com/vmware/vipclient/i18n/util/FormatUtils.java
  src/test/java/com/vmware/vip/i18n/MessageFormatTest.java
Labels: cla-not-required

#632 [BUG] [Service] No "numberingSystems" data when reqeust "Currencies" pattern #630
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/pattern/PatternServiceImpl.java
Labels: cla-not-required

#633 upgrade the jar of singleton server
  g11n-ws/modules/md-restful-api-i18n/build.gradle
  g11n-ws/modules/md-restful-synch/build.gradle
  g11n-ws/modules/md-service-authen/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#615 Add introduction document of singleton csharp client sdk
  content/en/docs/overview/singleton-sdk/csharp-client-introduction.md
Labels: cla-not-required
