Repository vmware/singleton, pull requests merged in 2020-04, with the labels that each got.

#490 print metric quality summary for each project
  sonar/check_sonar_qualitygate.py
Labels: area/ci, cla-not-required

#488 enhance cache control value
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/Interceptor/APICacheControlInterceptor.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/WebConfiguration.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/APICacheControlInterceptor.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteWebConfiguration.java
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#492 add debug level test log, remove html report display
  .travis.yml
  build.gradle
Labels: area/ci, cla-not-required

#497 add test log and remove progress bar
  .travis.yml
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n-agent/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: area/ci, cla-not-required

#496 add license information to testing code
  singletonclient/ClientTestApp/Program.cs
  singletonclient/ClientTestApp/Properties/AssemblyInfo.cs
  singletonclient/Product1ResLib/Function1.cs
  singletonclient/Product1ResLib/Properties/AssemblyInfo.cs
  singletonclient/Product1ResLib/Util1.cs
  singletonclient/Product2ResLib/Function2.cs
  singletonclient/Product2ResLib/Properties/AssemblyInfo.cs
  singletonclient/Product2ResLib/Util2.cs
  singletonclient/SingletonClient/Properties/AssemblyInfo.cs
  singletonclient/SingletonIcu/AssemblyInfo.cpp
  singletonclient/SingletonIcu/pch.cpp
  singletonclient/UnitTestSingleton/BaseIo.cs
  singletonclient/UnitTestSingleton/Properties/AssemblyInfo.cs
  singletonclient/UnitTestSingleton/TestBaseIo.cs
  singletonclient/UnitTestSingleton/TestClient.cs
  singletonclient/UnitTestSingleton/TestSupport.cs
  singletonclient/UnitTestSingleton/Util.cs
  singletonclient/UnitTestSingletonIcu/Properties/AssemblyInfo.cs
  singletonclient/UnitTestSingletonIcu/TestBase.cs
  singletonclient/UnitTestSingletonIcu/TestDateTime.cs
  singletonclient/UnitTestSingletonIcu/TestNumber.cs
  singletonclient/UnitTestSingletonIcu/TestPlural.cs
  singletonclient/UnitTestSingletonIcu/TestRelativeDateTime.cs
Labels: cla-not-required

#501 Check parameter scope for APIs
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationWithPatternAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/formatting/pattern/FormattingPatternAPI.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsMsg.java
Labels: cla-not-required

#500 add go-client-introduction.md
  content/en/docs/overview/singleton-sdk/go-client-introduction.md
Labels: cla-not-required

#487 Improve readme
  README.md
Labels: area/service, kind/documentation

#508 remove en fallback from single component service
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/singlecomponent/OneComponentService.java
Labels: cla-not-required

#502 Add Deprecated for post method get translation and patterns
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/combine/TranslationWithPatternAPI.java
Labels: cla-not-required

#513 Add Singleton-JSClient 0.4.1
  CHANGELOG-0.4.md
Labels: cla-not-required

#510 add arguments to support more flexable filter
  check_headers.py
Labels: cla-not-required

#516 change log level to 'warn' to reduce log size
  .travis.yml
Labels: area/devops, cla-not-required

#519 add key script start and end mark
  .travis.yml
Labels: area/ci, cla-not-required

#523 add key script start and end mark
  .travis.yml
Labels: area/ci, cla-not-required

#522 add key script start and end mark
  .travis.yml
Labels: area/ci, cla-not-required

#521 add key script start and end mark
  .travis.yml
Labels: area/ci, cla-not-required

#524 Update test according to component api fallback behavior changes from en to nothing in service
  autotest/client/jscoresdk/test/translation.spec.ts
  autotest/client/jscoresdk/utils/constants.ts
Labels: cla-not-required

#479 [JsClient] Support downloading both translations and patterns by only…
  cli/load-locale-data.js
  package.json
  samples/client/js/README.md
  samples/client/js/html/example.html
  samples/client/js/index.js
  samples/client/js/package.json
  samples/client/js/src/config.js
  samples/client/js/src/i18n.utils.js
  samples/client/js/src/source.l10n.js
  samples/client/js/test/i18n.utils.test.js
  samples/client/js/webpack.config.js
  samples/server/express/README.md
  samples/server/express/i18n/i18nHandler.js
  samples/server/express/i18n/source.l10n.js
  samples/server/express/index.js
  samples/server/express/package.json
  src/configuration.ts
  src/constants.ts
  src/formatters/message.formatter.ts
  src/parser.ts
  src/services/core.service.ts
  test/__mocks__/axios.ts
  test/client.spec.ts
  test/loader.spec.ts
  test/parser.spec.ts
  test/plugins.mock.ts
  test/plurals.func.spec.ts
  webpack.config.js
Labels: cla-not-required

#520 add key script start and end mark
  .travis.yml
Labels: area/ci, cla-not-required

#475 Improve cache and local bundles
  README.md
  bundle_dao.go
  bundle_test.go
  cache_default.go
  cache_info.go
  cache_interface.go
  cache_sync.go
  cache_test.go
  common.go
  config.go
  config_test.go
  consts.go
  data_default.go
  data_service.go
  data_test.go
  go.mod
  go.sum
  httpclient.go
  httpclient_test.go
  inst.go
  inst_test.go
  interfaces.go
  logger_test.go
  messages.go
  server_dao.go
  server_test.go
  testdata/conf/config.json
  testdata/conf/config.yaml
  testdata/conf/config2.yaml
  testdata/mock/__files/componentMessages-RefreshCache-sunglow.json
  testdata/mock/__files/componentMessages-RefreshCacheSecondTime-sunglow.json
  testdata/mock/__files/componentMessages-en-US-sunglow.json
  testdata/mock/__files/componentMessages-fr-sunglow.json
  testdata/mock/__files/componentMessages-fr-users.json
  testdata/mock/__files/componentMessages-zh-Hans-HTTP404.json
  testdata/mock/__files/componentMessages-zh-Hans-WrongResponseContent.json
  testdata/mock/__files/componentMessages-zh-Hans-sunglow-HTTP304.json
  testdata/mock/__files/componentMessages-zh-Hans-sunglow-decodeerror.json
  testdata/mock/__files/componentMessages-zh-Hans-sunglow-pseudo.json
  testdata/mock/__files/componentMessages-zh-Hans-sunglow.json
  testdata/mock/mappings/componentMessages.json
  testutil_test.go
  translation.go
  translation_interface.go
  translation_test.go
Labels: cla-not-required

#512 Add a new query parameter scopeFilter to the pattern API
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationWithPatternAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v1/formatting/pattern/FormattingPatternAPI.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/combine/TranslationWithPatternAPI.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/formatting/pattern/FormattingPatternAPI.java
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/APIParamName.java
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/APIParamValue.java
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/pattern/IPatternService.java
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/pattern/PatternServiceImpl.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/dto/TranslationWithPatternDTO.java
Labels: cla-not-required

#531 Remove samples and test when npm pack
  .npmignore
  package.client.json
Labels: cla-not-required

#511 Loading offline resource bundles
  sample-client-app/src/main/java/com/vmware/vipclient/sample/Main.java
  sample-client-app/src/main/resources/offlineBundles/default/messages_en-US.json
  sample-client-app/src/main/resources/offlineBundles/default/messages_fil.json
  sample-client-app/src/main/resources/offlineBundles/default/messages_fr.json
  src/main/java/com/vmware/vipclient/i18n/I18nFactory.java
  src/main/java/com/vmware/vipclient/i18n/VIPCfg.java
  src/main/java/com/vmware/vipclient/i18n/base/DataSourceEnum.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/MessageCache.java
  src/main/java/com/vmware/vipclient/i18n/base/cache/MessageCacheItem.java
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/BaseOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/MessageOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalMessagesOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/ComponentBasedOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/dto/MessagesDTO.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/CacheService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/StringService.java
  src/main/java/com/vmware/vipclient/i18n/util/FileUtil.java
  src/main/java/com/vmware/vipclient/i18n/util/FormatUtils.java
  src/main/java/com/vmware/vipclient/i18n/util/JSONBundleUtil.java
  src/test/java/com/vmware/vip/i18n/HttpRequesterTest.java
  src/test/java/com/vmware/vip/i18n/SharedComponentTest.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
  src/test/java/com/vmware/vip/i18n/VIPCfgTest.java
  src/test/java/com/vmware/vipclient/i18n/messages/service/CacheServiceTest.java
  src/test/java/com/vmware/vipclient/i18n/messages/service/OfflineModeTest.java
  src/test/resources/log4j.properties
  src/test/resources/messages.properties
  src/test/resources/messages2.properties
  src/test/resources/messages3.properties
  src/test/resources/offlineBundles/JAVA/messages_fil.json
  src/test/resources/vipconfig-no-cache-expired-time.properties
  src/test/resources/vipconfig-offline.properties
  src/test/resources/vipconfig-online-offline.properties
Labels: cla-not-required
