Repository vmware/singleton, pull requests merged in 2020-03, with the labels that each got.

#405 remove new code quality gate
  sonar/quality_gates/java-client.json
  sonar/quality_gates/service_quality_gate.json
Labels: cla-not-required

#399 Add new document: singleton-service-script.md
  content/en/docs/overview/singleton-service/singleton-service-script.md
Labels: cla-not-required

#408 update quality gate for java client
  sonar/config_sonar_project.py
  sonar/quality_gates/java-client.json
Labels: cla-not-required

#409 fix jacoco xml report path issue, and use environment variable direct…
  .travis.yml
  build.gradle
Labels: cla-not-required

#410 use sonar token directly instead of addons
  .travis.yml
Labels: cla-not-required

#398 Add missed license and copyright headers
  src/main/java/com/vmware/vipclient/i18n/exceptions/VIPClientInitException.java
Labels: cla-not-required

#406 Update README.md
  README.md
Labels: cla-not-required

#412 Update Readme
  README.md
Labels: cla-not-required

#414 add jacoco test report task to subprojects
  .travis.yml
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#416 change log levle to 'trace'
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/LocaleService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/PatternService.java
Labels: cla-not-required

#413 add doc of response codes
  g11n-ws/docs/Service Response Code Specification.pdf
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
Labels: cla-not-required

#417 Update test cases for Service: version fallback
  autotest/service/i18n-service/APITest/resource/master/Testdata.xlsx
Labels: cla-not-required

#418 Add new test cases configuration
  autotest/service/i18n-service/APITest/resource/master/APIV2.json
Labels: cla-not-required

#388 add and format the version fallback APIs
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/BaseAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationWithPatternAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/locale/LocaleAPI.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/status/APIResponseStatus.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v2/combine/TranslationWithPatternTest.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductAPITest.java
Labels: cla-not-required

#422 add license and copyright checker
  check_headers.py
Labels: cla-not-required

#424 upgrade tomcat libs
  g11n-ws/modules/md-restful-api-i18n/build.gradle
  g11n-ws/modules/md-restful-synch/build.gradle
  g11n-ws/modules/md-service-authen/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#421 Remove getting multiple components' translation
  data_service.go
  interfaces.go
  translation.go
Labels: cla-not-required

#423 Miss copyright and license headers
  g11n-ws/modules/md-data-initdb/src/main/resources/scripts/__init__.py
  g11n-ws/modules/md-data-initdb/src/main/resources/scripts/pseudodb.py
  g11n-ws/scripts/singletonall.sh
  g11n-ws/scripts/singletoncheck.sh
  g11n-ws/scripts/singletonstart.sh
  g11n-ws/scripts/singletonstop.sh
Labels: cla-not-required

#427 Check changed files within travis push or pull request
  check_headers.py
Labels: area/devops, cla-not-required

#428 add header check stage
  .travis.yml
Labels: area/go-client, cla-not-required

#432 add header check stage
  .travis.yml
Labels: area/service, cla-not-required

#433 add header check stage
  .travis.yml
Labels: area/js-client, cla-not-required

#434 add header check stage
  .travis.yml
Labels: area/angular-client, cla-not-required

#437 add stage of checking header
  .travis.yml
Labels: area/java-client

#385 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-not-required

#457 [BUG] [GetSupportedLanguageList] No displayName for zh-Hant when leave displayLanguage empty
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/locale/LocaleService.java
Labels: cla-not-required

#458 [BUG] [GetSupportedLanguageList] some data titlecase of displayName is inconsistent with rule that defined in CLDR
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/locale/LocaleService.java
Labels: cla-not-required

#456 add parameter verification for get translation with pattern API
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationWithPatternAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/utils/ParameterValidationUtility.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/URLValidation.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
Labels: cla-not-required

#460 update README
  README.md
Labels: cla-not-required

#459 update README
  README.md
Labels: cla-not-required

#466 refactory and suppport more customized argument
  check_headers.py
Labels: cla-not-required

#465 Add etag/max-age in Translation APIs response
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/Interceptor/APICacheControlInterceptor.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/WebConfiguration.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/APICacheControlInterceptor.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/conf/LiteWebConfiguration.java
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#467 [JsClient] remove multiple component support
  README.md
  package-lock.json
  package.client.json
  package.json
  samples/client/js/README.md
  samples/client/js/package-lock.json
  samples/client/js/package.json
  samples/server/express/README.md
  samples/server/express/package-lock.json
  samples/server/express/package.json
  src/client.ts
  src/configuration.ts
  src/parser.ts
  src/services/core.service.ts
  src/services/l10n.service.ts
  test/plugins.mock.ts
Labels: cla-not-required

#470 remove sonar addon out of date
  .travis.yml
Labels: cla-not-required

#471 add go and csharp quality gates
  sonar/quality_gates/csharp-client.json
  sonar/quality_gates/go-client.json
Labels: cla-not-required

#472 configure sonar scanner
  .travis.yml
Labels: area/go-client, cla-not-required

#473 remove sonar addon which usage is out of date and filter deleted files
  .travis.yml
Labels: area/angular-client, cla-not-required

#476 filter deleted files for header check
  .travis.yml
Labels: area/devops, area/service, cla-not-required

#477 filter deleted files and update sonar project name
  .travis.yml
Labels: area/devops, area/java-client, cla-not-required

#478 filter deleted files for header check
  .travis.yml
Labels: area/devops, area/js-client, cla-not-required

#480 add new validate for singleton service
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/RegExpValidatorUtils.java
Labels: cla-not-required
