Repository vmware/singleton, pull requests merged in 2020-12, with the labels that each got.

#886 save L10n resources to Amazon S3
  .gitignore
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/dto/SingleComponentDTO.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/TimeUtils.java
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/RsaCryptUtil.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/S3Client.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/WebConfiguration.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/service/RecordServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/crons/SourceSendingCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/SourceDao.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/LocalSourceDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/S3SourceDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/SourceDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/RemoteSyncServicempl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SourceServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/controller/TranslationSyncServerController.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/SingleComponentDao.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/impl/LocalSingleComponentDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/impl/S3SingleComponentDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/service/TranslationSyncServerService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/service/impl/TranslationSyncServerServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/MapUtil.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/S3Util.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/SourceUtils.java
  g11n-ws/vip-manager-l10n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application.properties
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/S3Test.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/SourceDaoTest.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/SourceSendingCronTest.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/SourceServiceTest.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/TranslationControllerTest.java
Labels: cla-not-required

#892 Add gradle files and CI file to branch g11n-cldr-pattern
  .travis.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: cla-not-required

#888 Fixed the s3 configuration item name
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/RsaCryptUtils.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/S3Config.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
Labels: cla-not-required

#880 upload external pattern lib smoke test
  autotest/cldrpattern/ExtractedPatternLibTestCases.xlsx
  autotest/cldrpattern/HTMLTestRunner.py
  autotest/cldrpattern/constant.py
  autotest/cldrpattern/excelutility.py
  autotest/cldrpattern/test.py
Labels: cla-not-required

#883 Adding build file to sample-app-with-shared-lib to build it as Spring Boot app
  sample-client-app/sample-app-with-shared-lib/README.md
  sample-client-app/sample-app-with-shared-lib/build-spring-boot.gradle
  sample-client-app/sample-app-with-shared-lib/build.gradle
  sample-client-app/sample-app-with-shared-lib/src/main/java/com/vmware/vipclient/sample/springboot/Application.java
Labels: area/java-client, cla-not-required, kind/bug, priority/high

#869 Bug 868 [BUG] The offlineResourceBaseURL inside a shared lib is not being read if either main app is is run from IDE or executable jar has nested jars like in spring boot
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalProductOpt.java
  src/main/java/com/vmware/vipclient/i18n/util/FileUtil.java
Labels: area/java-client, cla-not-required, kind/bug, priority/high

#900 Fix issue #899
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/S3SourceDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/SingleComponentDao.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/impl/LocalSingleComponentDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/impl/S3SingleComponentDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/service/impl/TranslationSyncServerServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/S3Util.java
Labels: cla-not-required

#878 Non-blocking getSupportedLocales + Use getResourceAsStream to read resource bundle
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalLocaleOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalMessagesOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalProductOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ProductService.java
  src/main/java/com/vmware/vipclient/i18n/util/LocaleUtility.java
Labels: area/java-client, cla-not-required, kind/bug, kind/enhancement, priority/high

#906 Fix issue #842
  g11n-ws/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#890 improve handling of locale and meet the requirement of SonarQube
  singletonclient/ClientTestApp/ClientTestApp.csproj
  singletonclient/Product1ResLib/Function1.cs
  singletonclient/Product1ResLib/Util1.cs
  singletonclient/Product2ResLib/Util2.cs
  singletonclient/SingletonClient/I18n.cs
  singletonclient/SingletonClient/IConfig.cs
  singletonclient/SingletonClient/IExtension.cs
  singletonclient/SingletonClient/IReleaseMessages.cs
  singletonclient/SingletonClient/ITranslation.cs
  singletonclient/SingletonClient/Implementation/Helpers/CultureHelper.cs
  singletonclient/SingletonClient/Implementation/SingletonAccessRemoteTask.cs
  singletonclient/SingletonClient/Implementation/SingletonApi.cs
  singletonclient/SingletonClient/Implementation/SingletonClientManager.cs
  singletonclient/SingletonClient/Implementation/SingletonComponent.cs
  singletonclient/SingletonClient/Implementation/SingletonConfig.cs
  singletonclient/SingletonClient/Implementation/SingletonConst.cs
  singletonclient/SingletonClient/Implementation/SingletonRelease.cs
  singletonclient/SingletonClient/Implementation/SingletonRes/fallback.yml
  singletonclient/SingletonClient/Implementation/SingletonSource.cs
  singletonclient/SingletonClient/Implementation/SingletonUpdate.cs
  singletonclient/SingletonClient/Implementation/SingletonUtil.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonCacheComponentManager.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonCacheComponentMessages.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonCacheLocaleMessages.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonCacheManager.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonCacheReleaseMessages.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonLocale.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonParserProperties.cs
  singletonclient/SingletonClient/SingletonClient.csproj
  singletonclient/UnitTestSingleton/BaseIo.cs
  singletonclient/UnitTestSingleton/TestBaseIo.cs
  singletonclient/UnitTestSingleton/TestClient.cs
  singletonclient/UnitTestSingleton/Util.cs
  singletonclient/UnitTestSingletonIcu/UnitTestSingletonIcu.csproj
Labels: cla-not-required

#909 fixed the base64 decode issue in windows
  g11n-ws/modules/md-data-api-s3impl/build.gradle
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/RsaCryptUtils.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/S3Config.java
Labels: cla-not-required

#913 Fix Windows bug on getComponentMessages
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalMessagesOpt.java
Labels: area/java-client, cla-not-required, kind/bug, priority/high

#911 fix issue 658 about getting component list
  singletonclient/SingletonClient/Implementation/SingletonUpdate.cs
  singletonclient/SingletonClient/Implementation/SingletonUtil.cs
Labels: cla-not-required

#901 Add L10n s3 access key encryption
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/RsaCryptUtil.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/S3Cfg.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/S3Client.java
Labels: cla-not-required

#902 Support reading allow list from S3
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/WebConfiguration.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/S3Util.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/WhiteListUtils.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestUtils.java
Labels: cla-not-required

#917 [Devops][cldr pattern] Create quality gate jason file for g11n-cldr-pattern branch
  sonar/quality_gates/cldr-pattern.json
Labels: area/devops, cla-not-required

#918 [Devops][g11n-cldr-pattern] Add unit test and code scan jobs to CI of branch g11n-cldr-pattern
  .travis.yml
  build.gradle
Labels: area/devops, cla-not-required

#914 fix issue 657 about getting locale list and set YamlDotNet to v8.1.2
  singletonclient/SingletonClient/Implementation/SingletonUpdate.cs
  singletonclient/SingletonClient/SingletonClient.csproj
  singletonclient/SingletonClient/packages.config
Labels: cla-not-required

#920 fix issue 587 to check null pointer in Format()
  singletonclient/SingletonClient/Implementation/SingletonRelease.cs
Labels: cla-not-required

#862 fix issue 841
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalLocaleOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalPatternOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/RemoteLocaleOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/RemotePatternOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/LocaleService.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/PatternService.java
Labels: cla-not-required

#926 Fix bug #923 [l10n][s3] 520 Unknow error for all APIs
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/S3Client.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/expt/ExceptionHandle.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/S3SourceDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/impl/S3SingleComponentDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/S3Util.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/WhiteListUtils.java
Labels: cla-not-required

#928 Update cldr-pattern test case as cldr data is stored with zip format
  autotest/cldrpattern/ExtractedPatternLibTestCases.xlsx
  autotest/cldrpattern/constant.py
  autotest/cldrpattern/excelutility.py
  autotest/cldrpattern/test.py
Labels: cla-not-required

#924 recreate singleton client project to let it become a nuget project
  singletonclient/ClientTestApp/ClientTestApp.csproj
  singletonclient/ClientTestApp/packages.config
  singletonclient/Product1ResLib/Product1ResLib.csproj
  singletonclient/Product1ResLib/packages.config
  singletonclient/Product2ResLib/Product2ResLib.csproj
  singletonclient/SingletonClient.sln
  singletonclient/SingletonClient/Properties/AssemblyInfo.cs
  singletonclient/SingletonClient/SingletonClient.csproj
  singletonclient/SingletonClient/app.config
  singletonclient/SingletonClient/license/license.txt
  singletonclient/SingletonClient/packages.config
  singletonclient/UnitTestSingleton/UnitTestSingleton.csproj
  singletonclient/UnitTestSingleton/packages.config
Labels: cla-not-required

#938 [pattern]fix the usage for python 3.4 compatibility
  autotest/cldrpattern/test.py
Labels: cla-not-required

#939 [pattern] throw exit code for CI pipe use
  autotest/cldrpattern/test.py
Labels: cla-not-required
