Repository vmware/singleton, pull requests merged in 2021-01, with the labels that each got.

#943 fix issue 856 to properly load in local bundles
  singletonclient/SingletonClient/IReleaseMessages.cs
  singletonclient/SingletonClient/Implementation/SingletonRelease.cs
  singletonclient/SingletonClient/Implementation/SingletonUpdate.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonCacheLocaleMessages.cs
  singletonclient/SingletonClient/Implementation/Support/SingletonCacheReleaseMessages.cs
  singletonclient/UnitTestSingleton/TestBaseIo.cs
Labels: cla-not-required

#947 fix issue 930 to correctly load in component list and locale list of …
  singletonclient/SingletonClient/Implementation/SingletonUpdate.cs
Labels: cla-not-required

#944 fix unit test failure in DateFormatUtilOfflineTest
  src/main/java/com/vmware/vipclient/i18n/l2/text/parser/DateStrPatternParser.java
  src/test/java/com/vmware/vip/i18n/DateFormatUtilOfflineTest.java
Labels: area/java-client, cla-not-required, kind/bug

#942 [Devops][g11n-cldr-pattern] Add smoke test job to CI
  .travis.yml
Labels: area/cldr-pattern, area/devops, cla-not-required

#957 Update copyright year to 2021
  bundle_dao.go
  bundle_test.go
  cache_default.go
  cache_info.go
  cache_interface.go
  cache_service.go
  cache_test.go
  common.go
  config.go
  config_test.go
  consts.go
  data_default.go
  data_test.go
  httpclient.go
  httpclient_test.go
  inst.go
  inst_test.go
  logger_default.go
  logger_test.go
  messages.go
  server_dao.go
  server_test.go
  testutil_test.go
  translation.go
  translation_interface.go
  translation_manager.go
  translation_test.go
Labels: cla-not-required

#952 [service] upgrade singleton service dependency jars
  g11n-ws/build.gradle
  g11n-ws/modules/md-restful-api-i18n/build.gradle
  g11n-ws/modules/md-service-authen/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#949 Fix bug #932 [L10n][S3] Failed to save the translation content to S3 storage
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/controller/TranslationSyncServerController.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/dao/impl/S3SingleComponentDaoImpl.java
Labels: cla-not-required

#937 fix version api bugs: 933, 935
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/BaseAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/about/AboutVersionAPI.java
  g11n-ws/modules/md-service-about/src/main/java/com/vmware/vip/core/about/service/version/IVersionService.java
  g11n-ws/modules/md-service-about/src/main/java/com/vmware/vip/core/about/service/version/VersionService.java
  g11n-ws/vip-manager-i18n/src/main/resources/application.properties
  g11n-ws/vip-manager-lite-i18n/src/main/resources/application.properties
Labels: area/service, cla-not-required

#963 Unify the data type of 'data' node for API success&failure response
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/core/except/ExceptionHandle.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/BaseAction.java
  g11n-ws/modules/md-restful-synch/src/main/java/com/vmware/vip/i18n/api/v2/synch/TranslationSynchController.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/dto/response/APIResponseDTO.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/expt/ExceptionHandle.java
Labels: area/service, cla-not-required, kind/bug

#959 [g11n-cldr-pattern]fixed the scan bugs
  src/main/java/com/vmware/i18n/cldr/CLDR.java
  src/main/java/com/vmware/i18n/locale/action/LocaleAction.java
  src/main/java/com/vmware/i18n/pattern/action/PatternAction.java
  src/main/java/com/vmware/i18n/utils/CLDRUtils.java
  src/main/java/com/vmware/i18n/utils/LocaleDataUtils.java
  src/main/java/com/vmware/i18n/utils/MiscUtils.java
  src/main/java/com/vmware/i18n/utils/timezone/CldrTimeZoneUtils.java
  src/test/java/com/vmware/i18n/PatternParseMainTest.java
Labels: cla-not-required

#967 fix bug 966: [BUG] [Service]Value "null" is assigned when productName or version is undefined in About API.
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/about/AboutVersionAPI.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsMsg.java
Labels: area/service, cla-not-required, kind/bug

#874 Namedargs - built on top of Xiaochao's PR: #865
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentService.java
  src/main/java/com/vmware/vipclient/i18n/util/FormatUtils.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
  src/test/resources/mockserver/__files/body-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0-locales-de-components-JAVA-971r6.json
  src/test/resources/mockserver/__files/body-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0-locales-en-components-JAVA-txB30.json
Labels: cla-not-required

#950 [l10n agent] [l10n]add the l10n agent sync source from i10n manager s3 storage feature
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/l10n/L10nI18nAPI.java
  g11n-ws/vip-manager-l10n-agent/build.gradle
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/base/PropertyContantKeys.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/base/TaskSysnQueues.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/conf/PropertyConfigs.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/model/RecordModel.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/MutiThreadReqApiV1.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/RecordService.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/RecordServiceImpl.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/SingleComponentService.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/SingleComponentServiceImpl.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/utils/HttpRequester.java
  g11n-ws/vip-manager-l10n-agent/src/main/resources/application.properties
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/controller/RecordController.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/dao/SqlLiteDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/model/RecordModel.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/service/RecordService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/service/RecordServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/SourceDao.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/LocalSourceDaoImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/S3SourceDaoImpl.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/RecordControllerTest.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestModels.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestUtils.java
Labels: cla-not-required

#940 Adding support for ResourceBundle source
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/test/java/com/vmware/vipclient/i18n/messages/service/OfflineModeTest.java
  src/test/resources/offlineBundles/JAVA2/messages.properties
  src/test/resources/offlineBundles/JAVA2/messages_en.json
  src/test/resources/offlineBundles/JAVA2/messages_fil.json
  src/test/resources/offlineBundles/JAVA2/subdir/messages.properties
Labels: area/java-client, cla-not-required, priority/medium

#969 upgrade the fastjson Jar
  g11n-ws/vip-manager-l10n-agent/build.gradle
Labels: cla-not-required

#968 update i18n dependency jar icu4j to 60.3
  g11n-ws/modules/md-service-i18n-l2/build.gradle
Labels: cla-not-required

#960 add MT support for Intento
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/MTConfig.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/MTFactory.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/azure/AzureTranslatingProcessor.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/intento/ContextModel.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/intento/FromModel.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/intento/IntentoConfig.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/intento/IntentoConfigContent.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/intento/IntentoTranslatingProcessor.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/intento/Response.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/intento/ServiceModel.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/intento/ToResult.java
  g11n-ws/modules/md-data-api-mt/src/main/java/com/vmware/vip/messages/mt/transportal/PortalTranslatingProcessor.java
  g11n-ws/modules/md-data-api/src/main/java/com/vmware/vip/messages/data/dao/api/IMTProcessor.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/mt/MTService.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/http/HTTPRequester.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
Labels: cla-not-required

#970 [Devops][g11n-cldr-pattern] add checking sonar qualitygate
  .travis.yml
Labels: area/cldr-pattern, area/devops

#973 add the s3 encryt access key feature
  content/en/docs/overview/singleton-service/singleton-service-s3.md
Labels: cla-not-required

#977 fix bug 896 - Can't create json files when collect source or update translation for new product
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/product/ProductService.java
Labels: cla-not-required

#974 update API document for CSharp Client
  content/en/docs/overview/singleton-sdk/csharp-client-introduction.md
Labels: cla-not-required

#986 update code according to the improvement in CSharp Client: new config…
  README.md
  sgtn4python/sample/sample_app.py
  sgtn4python/sample/sample_offline_disk.yml
  sgtn4python/sample/sample_offline_remote.yml
  sgtn4python/sample/sample_online_offline.yml
  sgtn4python/sample/sample_online_only.yml
  sgtn4python/sgtn_client.py
  sgtn4python/sgtn_properties.py
  sgtn4python/sgtn_util.py
  sgtn4python/test/sgtn_client.yml
  sgtn4python/test/test_properties_parser.py
  sgtn4python/test/test_sgtn_client.py
  sgtn4python/test/test_sgtn_util.py
Labels: cla-not-required

#991 improve sample code
  sgtn4python/sample/sample_app.py
  sgtn4python/sample/sample_online_localsource.yml
  sgtn4python/sgtn_client.py
Labels: cla-not-required

#979 Update copyright for g11n-angular-client
  cli/collect-mixin-source.ts
  cli/collect-source-bundle.js
  cli/generate-token.js
  cli/load-i18n-package.js
  cli/translation-service.js
  cli/utils.js
  cli/vip.js
  config/helpers.js
  config/karma.conf.js
  config/spec-bundle.js
  config/testing-untils.ts
  config/webpack.test.js
  index.ts
  karma.conf.js
  src/config.ts
  src/constants.ts
  src/data/locale_en.ts
  src/exceptions.ts
  src/formatters/date.formatter.ts
  src/formatters/message.formatter.ts
  src/formatters/number.format.util.ts
  src/formatters/number.formatter.ts
  src/formatters/plural/plural.formatter.ts
  src/formatters/plural/plural.message.parser.ts
  src/formatters/plural/plurals.func.ts
  src/i18n.pipe.ts
  src/l10n.directive.ts
  src/l10n.pipe.ts
  src/loader.ts
  src/localized-component.mixin.ts
  src/response.parser.ts
  src/services/base.service.ts
  src/services/i18n.service.ts
  src/services/l10n.service.ts
  src/services/locale.service.ts
  src/services/vip.service.ts
  src/util.ts
  tests/datetime.format.spec.ts
  tests/i18n.service.spec.ts
  tests/l10n.directive.spec.ts
  tests/l10n.pipe.spec.ts
  tests/l10n.service.spec.ts
  tests/locale_de.ts
  tests/number.format.spec.ts
  tests/plural.spec.ts
  tests/test.util.ts
  tests/util.spec.ts
  tests/vip.loader.spec.ts
  tests/vip.service.spec.ts
  vmw-ngx-vip.module.ts
Labels: area/angular-client, cla-not-required

#980 Update copyright for g11n-js-client
  cli/collect-source-bundle.js
  cli/generate-token.js
  cli/load-i18n-package.js
  cli/load-locale-data.js
  cli/translation-service.js
  cli/utils.js
  cli/vip.js
  config/helpers.js
  index.ts
  samples/client/js/html/example.html
  samples/client/js/index.js
  samples/client/js/src/config.js
  samples/client/js/src/i18n.utils.js
  samples/client/js/src/source.l10n.js
  samples/client/js/test/i18n.utils.test.js
  samples/client/js/webpack.config.js
  samples/server/express/i18n/i18nHandler.js
  samples/server/express/i18n/source.l10n.js
  samples/server/express/index.js
  src/cache.ts
  src/client.ts
  src/configuration.ts
  src/constants.ts
  src/data/locale_en.ts
  src/exceptions.ts
  src/formatters/date.formatter.ts
  src/formatters/message.formatter.ts
  src/formatters/number.format.util.ts
  src/formatters/number.formatter.ts
  src/formatters/plural/plural.formatter.ts
  src/formatters/plural/plural.message.parser.ts
  src/formatters/plural/plurals.func.ts
  src/loader.ts
  src/logger.ts
  src/parser.ts
  src/services/core.service.ts
  src/services/i18n.service.ts
  src/services/l10n.service.ts
  src/utils.ts
  test/__mocks__/axios.ts
  test/cache.spec.ts
  test/client.spec.ts
  test/core.service.spec.ts
  test/date.format.spec.ts
  test/expection.spec.ts
  test/i18n.service.spec.ts
  test/l10n.service.spec.ts
  test/loader.spec.ts
  test/locale.de.ts
  test/message.format.spec.ts
  test/number.format.spec.ts
  test/parser.spec.ts
  test/plugins.mock.ts
  test/plural.spec.ts
  test/plurals.func.spec.ts
  test/util.spec.ts
  webpack.config.js
Labels: area/js-client, cla-not-required

#992 fix issue 787 to correctly use locale fallback table
  sgtn4python/sgtn_util.py
Labels: cla-not-required

#993 fix issue 786 to correctly use default locale when target locale mess…
  sgtn4python/sgtn_client.py
Labels: cla-not-required
