Repository vmware/singleton, pull requests merged in 2021-12, with the labels that each got.

#1382 G11n ruby client: add timezone, add getString_p for plural, bug fix, update sample codes
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/cldr/localized_datetime.rb
  lib/version.rb
  samples/Gemfile
  samples/README.md
  samples/config/locales/default/JAVA/default.yml
  samples/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_zh-Hans.json
  samples/config/sgtnclient.yml
  samples/formatting/all.rb
  samples/translation/all.rb
  spec/config/locales/default/JAVA/default.yml
  spec/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_de.json
  spec/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_en.json
  spec/unit/cache_spec.rb
  spec/unit/datetime_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/plural_spec.rb
Labels: cla-not-required

#1383 fix bug 1373: [BUG] [Java Service]Nothing is shown as displayName for "en-US"/"de-DE" locales that has short name(en/de) in its language itself.
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/locale/LocaleService.java
Labels: cla-not-required

#1358 PR1 of issue 990: [Java Client] Default to depend on English i18n formatting pattern in Java client
  build.gradle
  src/main/java/com/vmware/i18n/PatternConfig.java
  src/main/java/com/vmware/i18n/common/CLDRConstants.java
  src/main/java/com/vmware/i18n/locale/service/impl/LocaleServiceImpl.java
  src/main/java/com/vmware/i18n/pattern/service/impl/PatternServiceImpl.java
  src/main/java/com/vmware/i18n/utils/CLDRUtils.java
  src/main/java/com/vmware/i18n/utils/PathUtils.java
  src/test/java/com/vmware/i18n/PatternUtilTest.java
Labels: cla-not-required

#1387 Added CI
  .github/actions/get-branch-name-action/action.yml
  .github/actions/get-commit-range-action/action.yml
  .github/actions/were-only-docs-updated-action/action.yml
  .github/workflows/main.yml
Labels: cla-not-required

#1368 Added Github Actions
  .github/actions/get-branch-name-action/action.yml
  .github/actions/get-commit-range-action/action.yml
  .github/actions/were-only-docs-updated-action/action.yml
  .github/workflows/main.yml
Labels: cla-not-required

#1391 update code due to function is changed
  autotest/client/java/src/main/java/com/vmware/vip/test/javaclient/cache/CacheExpiredTest.java
Labels: cla-not-required

#1384 [angular client]add unit test
  projects/angular-client/karma.conf.js
  projects/angular-client/src/services/i18n.service.ts
  projects/angular-client/tests/datetime.format.spec.ts
  projects/angular-client/tests/i18n.context.spec.ts
  projects/angular-client/tests/i18n.pipe.spec.ts
  projects/angular-client/tests/i18n.service.spec.ts
  projects/angular-client/tests/l10n.pipe.spec.ts
  projects/angular-client/tests/l10n.service.spec.ts
  projects/angular-client/tests/locale.service.spec.ts
  projects/angular-client/tests/plural.formatter.spec.ts
  projects/angular-client/tests/plurals.func.spec.ts
  projects/angular-client/tests/vip.loader.spec.ts
Labels: cla-not-required

#1392 delete messages_pt-pt.json due to service issue #1364 to avoid blocki…
  autotest/client/jscoresdk/resources/bundles/JSCoreSDKTest/1.0.0/sunglow/messages_pt-PT.json
  autotest/client/jscoresdk/resources/bundles/JSCoreSDKTest/1.0.0/sunglow/messages_pt-pt.json
Labels: cla-not-required

#1394 Upgrade log4j to 2.15.0
  g11n-ws/build.gradle
Labels: cla-not-required, area/java-service

#1388 Add GitHub Action for g11n-js-client
  .github/actions/get-branch-name-action/action.yml
  .github/actions/get-commit-range-action/action.yml
  .github/actions/were-only-docs-updated-action/action.yml
  .github/workflows/node.js.yml
  codecov.yml
Labels: cla-not-required

#1396 [Python Document] Update to current status
  content/en/docs/overview/singleton-sdk/python-client-introduction.md
Labels: cla-not-required

#1397 [Python Client] Change version to 0.7.0 and make a small change.
  sgtn4python/setup.py
  sgtn4python/sgtnclient/sgtn_client.py
Labels: cla-not-required

#1398 upgrade log4j to 2.16.0
  g11n-ws/build.gradle
Labels: cla-not-required

#1400 shallow copying cities data to save time
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/locale/LocaleService.java
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/locale/TerritoryDTO.java
Labels: cla-not-required

#1402 optimize l2 cities data
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/locale/LocaleService.java
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/locale/TerritoriesFileParser.java
  g11n-ws/modules/md-service-i18n-l2/src/main/java/com/vmware/i18n/l2/service/locale/TerritoryDTO.java
  g11n-ws/vip-manager-lite-i18n/src/main/resources/ehcache3.xml
Labels: cla-not-required

#1390 Added CI
  .github/actions/get-branch-name-action/action.yml
  .github/actions/get-commit-range-action/action.yml
  .github/actions/were-only-docs-updated-action/action.yml
  .github/workflows/main.yaml
Labels: cla-not-required

#1412 upgrade log4j 2.16.0 to 2.17.0
  g11n-ws/build.gradle
  g11n-ws/vip-manager-l10n-agent/build.gradle
Labels: cla-not-required

#1414 Update java client smoke test code
  autotest/client/java/src/main/java/com/vmware/vip/test/javaclient/httprequester/CustomizeHeader.java
Labels: cla-not-required

#1413 Fixed the Null Pointer Exception in runtime
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/crons/SourceSendingCron.java
Labels: cla-not-required

#1393 add the allow list support product level
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsChar.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/resources/bundle.json
Labels: cla-not-required

#1415 fixed the NullPointerException
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/crons/SourceSendingCron.java
Labels: kind/bug, cla-not-required, area/java-service, priority/medium
