Repository vmware/singleton, pull requests merged in 2022-03, with the labels that each got.

#1561 change the l10n the schedule strategy
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/crons/SourceLocalBundleCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/crons/SourceSendGRMCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/crons/SourceSendI18nCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SyncGrmSourceServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SyncI18nSourceServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SyncLocalBundleServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
Labels: cla-not-required

#1553 Change the expected result of UTs related to MessageFormat and failed on CI server from hardcode values to dynamic values by using ICU4J
  build.gradle
  src/test/java/com/vmware/vip/i18n/MessageFormatOfflineTest.java
  src/test/java/com/vmware/vip/i18n/MessageFormatTest.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
Labels: cla-not-required

#1569 [Ruby client] Limit log file size to 1M and keep 4 files at most
  lib/sgtn-client/sgtn-client.rb
Labels: cla-not-required

#1578 fixed the bug of sourceformat insensitive
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsKeys.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
Labels: cla-not-required

#1581 add license headers
  Gemfile
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/t.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/cldr/core_ext.rb
  lib/sgtn-client/cldr/localized_date.rb
  lib/sgtn-client/cldr/localized_datetime.rb
  lib/sgtn-client/cldr/localized_str.rb
  lib/sgtn-client/cldr/localized_time.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/core/exceptions.rb
  lib/sgtn-client/core/logging.rb
  lib/sgtn-client/core/request.rb
  lib/sgtn-client/formatters/plurals/plural_formatter.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/cache-util.rb
  lib/sgtn-client/util/file-util.rb
  lib/sgtn-client/util/locale-util.rb
  lib/sgtn-client/util/validate-util.rb
  lib/singleton-ruby.rb
  lib/version.rb
  spec/spec_helper.rb
  spec/unit/cache_spec.rb
  spec/unit/config_spec.rb
  spec/unit/datetime_spec.rb
  spec/unit/inconfig_spec.rb
  spec/unit/locale_spec.rb
  spec/unit/logging_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
  spec/unit/plural_spec.rb
  spec/unit/request_spec.rb
  spec/unit/version_spec.rb
Labels: cla-not-required

#1551 [Ruby Client] Correct caching and usage of source vs. "en" bundles
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/util/cache-util.rb
  lib/sgtn-client/util/locale-util.rb
  spec/unit/cache_spec.rb
  spec/unit/locale_spec.rb
  spec/unit/onclient_spec.rb
Labels: cla-not-required

#1568 fix issue: throw expt when locale is nil
  lib/sgtn-client/api/source.rb
  spec/unit/source_spec.rb
Labels: cla-not-required

#1580 fixed the mult-key API bugs
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/string/IStringService.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/string/StringService.java
Labels: kind/bug, area/java-service, priority/high

#1585 Skip unit test in smoke test stage of GitHub Actions CI, remove legacy sonar cloud scanning
  .github/workflows/main.yml
  .github/workflows/sonar-scanning.yml
Labels: cla-not-required, area/ci

#1586 Fix failed to collect the key set is around 1.9MB
  g11n-ws/vip-manager-l10n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
Labels: cla-not-required

#1573 [Ruby Client] Dont' delete cache after cahce is expired
  lib/sgtn-client/core/cache.rb
Labels: kind/feature, priority/medium, area/ruby-client

#1588 Add # in key validate
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/RegExpValidatorUtils.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPIValidationInterceptor.java
Labels: cla-not-required

#1593 Fix #1575 File read does not support thread concurrency
  lib/sgtn-client/util/file-util.rb
  spec/unit/file_spec.rb
Labels: cla-not-required

#1579 allow one same request to server at the same time; add source comparison; revise locale utility
  .gitignore
  Gemfile
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/t.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/common.rb
  lib/sgtn-client/util/cache-util.rb
  lib/sgtn-client/util/file-util.rb
  lib/sgtn-client/util/locale-util.rb
  samples/Gemfile
  singleton-ruby.gemspec
  spec/config/locales/default/JAVA/default.yml
  spec/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_en.json
  spec/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_zh-Hans.json
  spec/spec_helper.rb
  spec/unit/cache_spec.rb
  spec/unit/locale_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
  spec/unit/plural_spec.rb
  spec/unit/source_spec.rb
Labels: kind/feature, priority/medium, area/ruby-client

#1592 add parameter keys validate
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/RegExpValidatorUtils.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPIValidationInterceptor.java
Labels: kind/bug, area/java-service, priority/medium

#1599 Revert validate exception response format
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/core/except/ExceptionHandle.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/expt/ExceptionHandle.java
Labels: cla-not-required

#1583 fix bug 1515: locale null exception and 1533: component null exception
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/common/ConstantsMsg.java
  src/main/java/com/vmware/vipclient/i18n/messages/dto/MessagesDTO.java
Labels: cla-not-required

#1611 [Devops]Modify the test code logic and remove some complex scenarios
  autotest/client/ruby/config/locales/default/about/default.yml
  autotest/client/ruby/config/locales/defaultoffline/about/default.yml
  autotest/client/ruby/config/sgtnclient.yml
  autotest/client/ruby/spec/SimpleT_offline_spec.rb
  autotest/client/ruby/spec/SimpleT_spec .rb
  autotest/client/ruby/spec/Translation_offline_spec.rb
  autotest/client/ruby/spec/Translation_spec.rb
Labels: cla-not-required

#1610 [Ruby Client] Fixing locale matching code
  lib/sgtn-client/util/locale-util.rb
  spec/unit/locale_spec.rb
Labels: cla-not-required, area/ruby-client

#1608 change locale of source bundle to source locle
  lib/sgtn-client/api/source.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
Labels: cla-not-required

#1612 Fixing 1602
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/util/string-util.rb
  spec/unit/plural_spec.rb
Labels: cla-not-required

#1600 upgrade spring boot to 2.5.10
  g11n-ws/build.gradle
Labels: cla-not-required

#1615 Revert the keys post validate
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
Labels: cla-not-required

#1614 cache code refactor
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/util/cache-util.rb
  spec/unit/inconfig_spec.rb
Labels: cla-not-required, area/ruby-client

#1628 fixed the lite source format
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPIValidationInterceptor.java
Labels: cla-not-required

#1633 add get multip keys api test case
  autotest/service/i18n-service/APITest/l10n/bundles/VMwareVIP2018/1.0/markdown/messages_de.json
  autotest/service/i18n-service/APITest/l10n/bundles/VMwareVIP2018/1.0/markdown/messages_en.json
  autotest/service/i18n-service/APITest/l10n/bundles/VMwareVIP2018/1.0/markdown/messages_es-419.json
  autotest/service/i18n-service/APITest/l10n/bundles/VMwareVIP2018/1.0/markdown/messages_ja.json
  autotest/service/i18n-service/APITest/l10n/bundles/VMwareVIP2018/1.0/markdown/messages_latest.json
  autotest/service/i18n-service/APITest/l10n/bundles/VMwareVIP2018/1.0/markdown/messages_zh-Hans.json
  autotest/service/i18n-service/APITest/resource/master/APIV2.json
  autotest/service/i18n-service/APITest/resource/master/Testdata.xlsx
Labels: cla-not-required

#1635 add some test data
  autotest/service/i18n-service/APITest/l10n/bundles/VMwareVIP2018/1.0/Test.ABC_abc-123/messages_de.json
  autotest/service/i18n-service/APITest/l10n/bundles/VMwareVIP2018/1.0/default/messages_de.json
Labels: cla-not-required

#1624 Add translation loader
  .gitignore
  Gemfile
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/common/single_operation.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/loader/local_bundle.rb
  lib/sgtn-client/loader/local_source_bundle.rb
  lib/sgtn-client/loader/server_bundle.rb
  lib/sgtn-client/loader/source_comparer.rb
  singleton-ruby.gemspec
  spec/config/locales/default/NEW/new.yml
Labels: cla-not-required, area/ruby-client
