Repository vmware/singleton, pull requests merged in 2022-02, with the labels that each got.

#1489 change ICollection to ICollection<string> and modify the case about G…
  autotest/client/csharp/CSharp/Function_test/Basic_method_test/GetComponentListoffline.cs
  autotest/client/csharp/CSharp/Function_test/Cache_management/GetComponentFromCache.cs
Labels: cla-not-required

#1492 re-order commit range
  .github/actions/get-commit-range-action/action.yml
Labels: cla-not-required

#1455 Implement issue 1424: Support format message with simple argument, which means argument format（type and style) can be specified in the argument placeholder.
  sample-client-app/src/main/java/com/vmware/vipclient/sample/TranslationDemo.java
  sample-client-app/src/main/resources/offlineBundles/default/messages_en.json
  sample-client-app/src/main/resources/offlineBundles/default/messages_source.json
  src/main/java/com/vmware/vipclient/i18n/base/instances/DateFormatting.java
  src/main/java/com/vmware/vipclient/i18n/base/instances/NumberFormatting.java
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
  src/main/java/com/vmware/vipclient/i18n/l2/service/NumberFormatService.java
  src/main/java/com/vmware/vipclient/i18n/l2/text/DateFormat.java
  src/main/java/com/vmware/vipclient/i18n/l2/text/MessageFormat.java
  src/main/java/com/vmware/vipclient/i18n/l2/text/MessagePattern.java
  src/main/java/com/vmware/vipclient/i18n/util/PatternProps.java
  src/test/java/com/vmware/vip/i18n/MessageFormatOfflineTest.java
  src/test/java/com/vmware/vip/i18n/MessageFormatTest.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
  src/test/resources/messages.properties
  src/test/resources/mockserver/__files/body-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0-locales-en-components-JAVA-txB30.json
  src/test/resources/mockserver/__files/body-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0-locales-zh-Hans-components-JAVA-voF7q.json
Labels: cla-not-required, area/java-service, kind/feature, priority/high

#1495 Fixing issue 1476 - An error is raised when locale argument is nil
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/util/locale-util.rb
  spec/unit/locale_spec.rb
  spec/unit/onclient_spec.rb
Labels: cla-not-required

#1505 Add support to icu format.
  sgtn4python/sample/l10n/PYTHON/1.0.0/about/messages.properties
  sgtn4python/sample/sample_app.py
  sgtn4python/sample/sample_offline_disk.yml
  sgtn4python/sgtnclient/I18N.py
  sgtn4python/sgtnclient/sgtn_client.py
  sgtn4python/sgtnclient/sgtn_icu.py
  sgtn4python/test/test_sgtn_icu.py
Labels: cla-not-required

#1508 Update tomcat jar to 9.0.58
  g11n-ws/build.gradle
Labels: cla-not-required

#1451 update the s3 account manage method
  g11n-ws/modules/md-data-api-s3impl/build.gradle
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/S3Cient.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/S3Client.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/S3Config.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3OneComponentDaoImpl.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3ProductDaoImpl.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/S3Cfg.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/S3Client.java
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
Labels: cla-not-required, area/java-service, kind/security

#1500 [I18n Service]fix issue 1463
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v1/translation/TranslationProductComponentKeyAPI.java
Labels: cla-not-required

#1517 [CSharp Client]Make sure 'zh_CN' correctly handled on Windows 2019 se…
  singletonclient/SingletonClient/Implementation/Helpers/CultureHelper.cs
Labels: cla-not-required

#1513 l10n support collection static files
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPI.java
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/APIOperation.java
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/APIParamName.java
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/APIParamValue.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsKeys.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/dto/KeySourceCommentDTO.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/l10n/source/dto/ComponentSourceDTO.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/SourceController.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/RemoteSyncServicempl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SourceServiceImpl.java
Labels: cla-not-required

#1520 G11n python client
  sgtn4python/sample/sample_app.py
  sgtn4python/sgtnclient/I18N.py
  sgtn4python/sgtnclient/sgtn_client.py
  sgtn4python/sgtnclient/sgtn_icu.py
  sgtn4python/sgtnclient/sgtn_util.py
  sgtn4python/test/test_sgtn_client.py
  sgtn4python/test/test_sgtn_icu.py
Labels: cla-not-required

#1511 Add generating source jar and javadoc jar script.
  build.gradle
Labels: cla-not-required

#1518 Add the multi-key query API
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPI.java
  g11n-ws/modules/md-restful-api/src/main/java/com/vmware/vip/api/rest/APIV2.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPITest.java
Labels: cla-not-required, area/java-service, kind/feature, priority/high

#1531 [Python Client] Add support of customized Logger.
  sgtn4python/sgtnclient/I18N.py
  sgtn4python/sgtnclient/sgtn_client.py
  sgtn4python/sgtnclient/sgtn_util.py
  sgtn4python/test/test_sgtn_client.py
Labels: cla-not-required

#1521 update the smoke test code beacuse pr 1495 and 1496
  autotest/client/ruby/spec/Default_cache_spec.rb
  autotest/client/ruby/spec/SimpleT_offline_spec.rb
  autotest/client/ruby/spec/SimpleT_spec .rb
  autotest/client/ruby/spec/Translation_offline_spec.rb
  autotest/client/ruby/spec/Translation_spec.rb
Labels: cla-not-required, area/devops

#1535 G11n python client
  sgtn4python/sgtnclient/sgtn_util.py
Labels: cla-not-required

#1543 G11n ruby client
  .github/actions/get-branch-name-action/action.yml
  .github/actions/get-commit-range-action/action.yml
  .github/actions/were-only-docs-updated-action/action.yml
  .github/workflows/main.yml
  Gemfile
  spec/spec_helper.rb
Labels: cla-not-required

#1547 [Python Client] Update README.md and the version.
  README.md
  sgtn4python/setup.py
Labels: cla-not-required, area/python-client, kind/documentation, priority/medium

#1538 add validate source format in service
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/core/except/ExceptionHandle.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPI.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/login/controller/AuthenticationLoginController.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/IVlidation.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/TokenValidation.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/URLValidation.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsKeys.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/exceptions/ValidationException.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/Interceptor/APIValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/expt/ExceptionHandle.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPIValidationInterceptor.java
Labels: cla-not-required
