Repository vmware/singleton, pull requests merged in 2022-07, with the labels that each got.

#1731 fix #1730 : substitute lumberjack for standard logger, substitude log_file, log_level for mode
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/core/logging.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/validate-util.rb
  lib/singleton-client.rb
  singleton-client.gemspec
  spec/config/sgtnclient-invalidate.yml
  spec/config/sgtnclient.yml
  spec/i18n_backend_spec.rb
  spec/support/helpers.rb
  spec/unit/cache_spec.rb
  spec/unit/config_spec.rb
  spec/unit/logging_spec.rb
  spec/unit/onclient_spec.rb
Labels: cla-not-required, area/ruby-client

#1677 launch only one thread when cache is expired
  Gemfile
  lib/sgtn-client/common/data.rb
  lib/sgtn-client/common/single_operation.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/loader.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/loader/loader_factory.rb
  lib/sgtn-client/loader/single_loader.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/cache-util.rb
  singleton-client.gemspec
  spec/autoload_spec.rb
  spec/loader/single_loader_spec.rb
  spec/singleton_spec.rb
  spec/spec_helper.rb
  spec/support/helpers.rb
  spec/support/shared_contexts.rb
  spec/support/utils.rb
  spec/unit/cache_spec.rb
  spec/unit/onclient_spec.rb
Labels: cla-not-required, area/ruby-client

#1696 upgrade jar to swagger3
  g11n-ws/build.gradle
  g11n-ws/modules/md-restful-api-db/build.gradle
  g11n-ws/modules/md-restful-api-i18n/build.gradle
  g11n-ws/modules/md-restful-synch/build.gradle
  g11n-ws/modules/md-service-authen/build.gradle
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/URLValidation.java
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/SwaggerConfig.java
  g11n-ws/vip-manager-i18n/src/main/java/com/vmware/vip/core/conf/WebConfiguration.java
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/Swagger2ToDocTest.java
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/SwaggerConfig.java
  g11n-ws/vip-manager-l10n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
Labels: cla-not-required

#1741 change validate key and validate keys to assii
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPI.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/RegExpValidatorUtils.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
  g11n-ws/vip-manager-lite-i18n/src/main/java/com/vmware/vip/core/Interceptor/LiteAPIValidationInterceptor.java
Labels: cla-not-required

#1758 fix i18n backend issue #1751 #1762
  lib/sgtn-client/i18n_backend.rb
Labels: cla-not-required, area/ruby-client

#1764 [angular client] update superagent version
  projects/angular-client/package.json
Labels: area/angular-client, kind/feature, priority/medium

#1765 [Go Sevice] upgrade Golang to 1.18
  api/v1/swagger/swagger.go
  api/v2/swagger/swagger.go
  go.mod
  go.sum
  tests/s3mock_test.go
Labels: cla-not-required, area/go-service

#1722 use blocks for debug level logs
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/server.rb
  lib/sgtn-client/loader/single_loader.rb
  lib/sgtn-client/loader/source.rb
  lib/sgtn-client/loader/source_comparer.rb
Labels: cla-not-required

#1682 improve available locales to match locales by component
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/i18n_backend.rb
  lib/sgtn-client/util/locale-util.rb
  lib/sgtn-client/util/string-util.rb
  singleton-client.gemspec
  spec/config/sgtnclient.yml
  spec/singleton_spec.rb
  spec/support/shared_contexts.rb
  spec/unit/config_spec.rb
  spec/unit/locale_spec.rb
  spec/unit/offclient_spec.rb
Labels: cla-not-required, area/ruby-client

#1778 [angular client] replace post api with get api
  projects/angular-client/package.json
  projects/angular-client/src/loader.ts
  projects/angular-client/tests/vip.loader.spec.ts
Labels: cla-not-required

#1782 [angular client] update readme
  README.md
Labels: cla-not-required, area/angular-client

#1779 upgrade tomcat lib
  g11n-ws/build.gradle
Labels: cla-not-required

#1747 add validate in put APIs
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationSyncAction.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/RegExpValidatorUtils.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/translation/controller/TranslationSyncServerController.java
Labels: cla-not-required

#1679 fixed checkout status issue
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentAction.java
Labels: cla-not-required

#1698 ignore the post combine api
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/combine/TranslationWithPatternAPI.java
Labels: cla-not-required

#1784 update jks content
  g11n-ws/vip-manager-i18n/src/main/resources/vip.jks
  g11n-ws/vip-manager-l10n/src/main/resources/vip.jks
  g11n-ws/vip-manager-lite-i18n/src/main/resources/vip.jks
Labels: cla-not-required

#1680 Source and translation are null when requesting inexistent key without source parameter
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v1/translation/TranslationProductComponentKeyAPI.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPI.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/i18n/dto/StringBasedDTO.java
Labels: cla-not-required

#1785 make cache thread safe
  lib/sgtn-client/common/data.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/cache-util.rb
  spec/loader/mix_spec.rb
  spec/spec_helper.rb
  spec/support/shared_contexts.rb
  spec/support/shared_examples_for_available_bundles.rb
  spec/support/utils.rb
  spec/unit/cache_spec.rb
  spec/unit/config_spec.rb
  spec/unit/onclient_spec.rb
Labels: cla-not-required, area/ruby-client

#1790 G11n java client javadoc format
  src/main/java/com/vmware/vipclient/i18n/base/instances/TranslationMessage.java
Labels: cla-not-required

#1791 Upgrade JSClient version in order to fix the issue on Jest Unit test
  package.client.json
  package.json
Labels: cla-not-required

#1713 add the doc source jar
  g11n-ws/tools/tool-cldr-extractor/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#1793 upgrade s3 depency jar
  g11n-ws/build.gradle
Labels: cla-not-required

#1795 using gem 'logging'
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/loader/cache.rb
  singleton-client.gemspec
Labels: cla-not-required, area/ruby-client

#1708 fixed get translation v1 locale not format
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/BaseAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentAction.java
Labels: cla-not-required

#1714 format source not provide msg
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/string/StringService.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsMsg.java
Labels: cla-not-required

#1798 Update javascript-client-introduction.md in consistent with JSClient upgrade
  .hugo_build.lock
  content/en/docs/overview/singleton-sdk/javascript-client-introduction.md
Labels: cla-not-required

#1799 bugfix for javascript-client-intorduction.md
  content/en/docs/overview/singleton-sdk/javascript-client-introduction.md
Labels: cla-not-required

#1803 fixed the request body issue
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPI.java
Labels: cla-not-required

#1806 fixed the source collect is true error when use get API
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/Interceptor/APISourceInterceptor.java
Labels: cla-not-required
