Repository vmware/singleton, pull requests merged in 2022-11, with the labels that each got.

#1924 singleton upgrade jackson-databind
  g11n-ws/build.gradle
Labels: cla-not-required

#1912 add csp token varification for PUT api
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/auth/interceptor/AuthInterceptor.java
Labels: cla-not-required

#1930 update config items and fix cache issue #1929
  api/server.go
  config/config_template.yaml
  internal/cache/cache_ristretto.go
  internal/config/config.go
  internal/logger/logger.go
  modules/cldr/constants.go
  modules/cldr/coreutil/cache/corecache.go
  modules/cldr/localeutil/cache/localecache.go
  tests/testdata/config/config.yaml
  tests/testutils_test.go
  tests/trans_test.go
Labels: cla-not-required, area/go-service

#1931 be able to update available components/locales cache to fix #1932
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/util/locale-util.rb
Labels: cla-not-required, area/ruby-client

#1937 upgrade the tomcat library
  g11n-ws/build.gradle
Labels: cla-not-required

#1938 apply IAM role to AWS S3 account
  config/config_template.yaml
  go.mod
  go.sum
  internal/config/config.go
  modules/translation/dao/dao.go
  modules/translation/dao/s3bundle/s3bundle.go
  modules/translation/dao/s3bundle/s3client.go
  modules/translation/dao/s3bundle/s3config.go
  modules/translation/dao/s3bundle/s3iface.go
  tests/s3_test.go
  tests/s3mock_test.go
  tests/testdata/config/config.yaml
Labels: cla-not-required, area/go-service

#1944 be able to update some keys in a bundle to fix #1942
  modules/translation/dao/decorator/decorator.go
  tests/testdata/config/config.yaml
  tests/trans_api_test.go
Labels: cla-not-required, area/go-service

#1947 return failed translations when querying product translation is partially successful to fix #1941
  api/v2/translation/handler_trans.go
  tests/api_test.go
Labels: cla-not-required, area/go-service

#1948 fix 1945: [Security][Java Client][CLDR-Pattern] Upgrade jackson-databind to latest version (2.14.0)
  build.gradle
Labels: cla-not-required

#1911 support pseudo feature
  .rubocop.yml
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/common/data.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/fallbacks.rb
  lib/sgtn-client/loader.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/loader/chain_loader.rb
  lib/sgtn-client/loader/consts.rb
  lib/sgtn-client/loader/loader_factory.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/pseudo.rb
  lib/sgtn-client/loader/server.rb
  lib/sgtn-client/loader/source.rb
  lib/sgtn-client/loader/source_comparer.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/localized_string.rb
  lib/singleton-client.rb
  lib/singleton-client/i18n_backend.rb
  lib/singleton-client/pseudo.rb
  spec/autoload_spec.rb
  spec/config/sgtnclient.yml
  spec/fallbacks_spec.rb
  spec/fixtures/mock_responses/JAVA-pseudo
  spec/i18n_backend_spec.rb
  spec/loader/mix_spec.rb
  spec/pseudo_spec.rb
  spec/raise_error_spec.rb
  spec/singleton_spec.rb
  spec/spec_helper.rb
  spec/support/helpers.rb
  spec/unit/cache_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
  spec/unit/request_spec.rb
Labels: cla-not-required, area/ruby-client

#1964 Remove codecov patch coverage condition check to fit cldr pattern's code case
  codecov.yml
Labels: cla-not-required

#1959 Update codecov.yml to fit latest format and integrate codacy check into GitHub Actions
  .github/workflows/main.yml
  codecov.yml
Labels: cla-not-required

#1963 change order of middlewares to print http response correctly to fix #1961
  lib/sgtn-client/loader/server.rb
Labels: cla-not-required, area/ruby-client

#1970 Update GitHub Actions CI to integrate codacy check and update codecov configure to fit patch coverage case in cldr pattern
  .github/workflows/gradle.yml
  codecov.yml
Labels: cla-not-required

#1960 Compatible with previous code which is able to read L2 bundle binded in pattern jar package to fix bug 1953 - Singleton service CI failure and Java Client offline mode failure
  src/main/java/com/vmware/i18n/utils/PathUtils.java
Labels: cla-not-required, area/cldr-pattern

#1950 jackson upgrade
  g11n-ws/build.gradle
  g11n-ws/modules/md-service-i18n-l2/build.gradle
Labels: cla-not-required

#1965 upgrade yaml
  g11n-ws/build.gradle
Labels: cla-not-required
