Repository vmware/singleton, pull requests merged in 2022-06, with the labels that each got.

#1723 fix #1718 support source in local translation
  lib/sgtn-client/loader/loader_factory.rb
  lib/sgtn-client/loader/local_translation.rb
  spec/fixtures/bundles/test/4.8.1/JAVA/messages_latest.json
  spec/fixtures/bundles/test/4.8.1/local_only/messages_latest.json
  spec/loader/mix_spec.rb
Labels: cla-not-required

#1724 Revert "speed up loading source (#1712)" to use YAML instead of psych_simple
  lib/sgtn-client/loader/source.rb
  singleton-ruby.gemspec
Labels: cla-not-required

#1732 fix unit test errors
  spec/fixtures/bundles/test/4.8.1/local_only/messages_latest.json
  spec/loader/mix_spec.rb
Labels: cla-not-required, area/ruby-client

#1676 upgrade the Sqllite version
  g11n-ws/build.gradle
Labels: cla-not-required

#1678 update l10n ssl jks file to l18n jks file
  g11n-ws/vip-manager-l10n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-l10n/src/main/resources/test.jks
  g11n-ws/vip-manager-l10n/src/main/resources/vip.jks
Labels: cla-not-required

#1738 change interface path to be relative rather than absolute
  lib/sgtn-client/loader/server.rb
  lib/sgtn-client/sgtn-client.rb
  spec/loader/mix_spec.rb
  spec/support/helpers.rb
Labels: cla-not-required, area/ruby-client

#1684 add a class to make Singleton function as I18n backends
  lib/sgtn-client/i18n_backend.rb
  lib/sgtn-client/sgtn-client.rb
  lib/singleton-client.rb
  singleton-ruby.gemspec
  spec/i18n_backend_spec.rb
Labels: cla-not-required, area/ruby-client

#1744 Update Gemfile
  autotest/client/ruby/Gemfile
Labels: cla-not-required

#1720 use a file to load a directory
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/t.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/common.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/core/logging.rb
  lib/sgtn-client/loader.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/loader/chain_loader.rb
  lib/sgtn-client/loader/loader_factory.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/server.rb
  lib/sgtn-client/loader/single_loader.rb
  lib/sgtn-client/loader/source.rb
  lib/sgtn-client/loader/source_comparer.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/cache-util.rb
  lib/sgtn-client/util/locale-util.rb
  lib/sgtn-client/util/validate-util.rb
  lib/singleton-ruby.rb
  samples/config/locales/default/JAVA/default.yml
  samples/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_en.json
  samples/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_zh-Hans.json
  samples/translation/all.rb
  spec/autoload_spec.rb
  spec/support/utils.rb
  spec/unit/cache_spec.rb
  spec/unit/datetime_spec.rb
  spec/unit/inconfig_spec.rb
  spec/unit/locale_spec.rb
  spec/unit/logging_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
  spec/unit/plural_spec.rb
  spec/unit/request_spec.rb
  spec/unit/source_spec.rb
  spec/unit/version_spec.rb
Labels: cla-not-required, area/ruby-client

#1745 set only one configuration item once
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/core/logging.rb
  lib/sgtn-client/i18n_backend.rb
  lib/sgtn-client/loader/loader_factory.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/server.rb
  lib/sgtn-client/loader/source.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/cache-util.rb
  lib/sgtn-client/util/locale-util.rb
  lib/sgtn-client/util/validate-util.rb
  lib/singleton-client.rb
  spec/config/sgtnclient.yml
  spec/i18n_backend_spec.rb
  spec/loader/available_bundles_spec.rb
  spec/loader/mix_spec.rb
  spec/singleton_spec.rb
  spec/support/helpers.rb
  spec/support/shared_contexts.rb
  spec/support/shared_examples_for_available_bundles.rb
  spec/unit/cache_spec.rb
  spec/unit/config_spec.rb
  spec/unit/locale_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
  spec/unit/plural_spec.rb
  spec/unit/request_spec.rb
  spec/unit/source_spec.rb
Labels: cla-not-required

#1748 G11n cldr pattern add source jar and java doc jar
  build.gradle
  codecov.yml
  src/test/java/com/vmware/test/i18n/PathUtilsTest.java
Labels: cla-not-required

#1753 G11n java client add publish script
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: cla-not-required

#1754 change singleton-ruby to singleton-client
  Gemfile
  Rakefile
  samples/Gemfile
  samples/formatting/all.rb
  singleton-client.gemspec
Labels: area/ruby-client
