Repository vmware/singleton, pull requests merged in 2022-04, with the labels that each got.

#1643 Remove unused MAC OS Generated files from Java Client Docs
  docs/overview/singleton-sdk/resources/java-client/0.6.1/.DS_Store
  docs/overview/singleton-sdk/resources/java-client/0.6.1/javadoc/.DS_Store
Labels: cla-not-required

#1646 upgrade the spring framework
  g11n-ws/build.gradle
Labels: cla-not-required

#1648 Update contributing guide about Java client document update
  CONTRIBUTING.md
Labels: cla-not-required

#1640 Implement mix mode
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/common/single_operation.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/core/request.rb
  lib/sgtn-client/exceptions.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/loader/chain_loader.rb
  lib/sgtn-client/loader/loader_factory.rb
  lib/sgtn-client/loader/local_bundle.rb
  lib/sgtn-client/loader/local_source_bundle.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/server.rb
  lib/sgtn-client/loader/server_bundle.rb
  lib/sgtn-client/loader/single_loader.rb
  lib/sgtn-client/loader/source.rb
  lib/sgtn-client/loader/source_comparer.rb
  lib/sgtn-client/util/file-util.rb
  lib/sgtn-client/util/locale-util.rb
  lib/sgtn-client/util/validate-util.rb
  lib/singleton-ruby.rb
  singleton-ruby.gemspec
  spec/config/locales/default/JAVA/default.yml
  spec/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_zh-Hans.json
  spec/config/locales/l10n/bundles/test/4.8.1/local_only/messages_en.json
  spec/config/locales/l10n/bundles/test/4.8.1/local_only/messages_zh-Hans.json
  spec/config/sgtnclient-invalidate.yml
  spec/config/sgtnclient.yml
  spec/fixtures/mock_responses/JAVA-en
  spec/fixtures/mock_responses/JAVA-zh-Hans
  spec/fixtures/mock_responses/component_only_on_server-en
  spec/fixtures/mock_responses/component_only_on_server-zh-Hans
  spec/fixtures/mock_responses/local_only-en
  spec/fixtures/mock_responses/local_only-zh-Hans
  spec/fixtures/mock_responses/nonexistent
  spec/mix_spec.rb
  spec/spec_helper.rb
  spec/unit/cache_spec.rb
  spec/unit/file_spec.rb
  spec/unit/logging_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
  spec/unit/plural_spec.rb
  spec/unit/request_spec.rb
  spec/unit/source_spec.rb
Labels: cla-not-required

#1655 java client java doc encoding error
  build.gradle
Labels: cla-not-required

#1657 upgrade jackson jar
  build.gradle
Labels: cla-not-required

#1662 fixed jaxb dependency jars
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#1659 Fixed the s3 get objectsummary mult-result
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3ProductDaoImpl.java
Labels: cla-not-required

#1641 upgrade to jackson to 2.12.6.1
  g11n-ws/build.gradle
  g11n-ws/tools/tool-cldr-extractor/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#1634 add the source format detail error msg
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
Labels: cla-not-required

#1629 add component validate in product translation api
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductAction.java
Labels: cla-not-required

#1650 Add supported locales and components
  Gemfile
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/common/data.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/loader/chain_loader.rb
  lib/sgtn-client/loader/consts.rb
  lib/sgtn-client/loader/loader_factory.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/server.rb
  lib/sgtn-client/loader/single_loader.rb
  lib/sgtn-client/loader/source.rb
  lib/sgtn-client/loader/source_comparer.rb
  lib/sgtn-client/util/cache-util.rb
  lib/sgtn-client/util/locale-util.rb
  spec/config/sgtnclient.yml
  spec/fixtures/mock_responses/componentlist
  spec/fixtures/mock_responses/local_only-en
  spec/fixtures/mock_responses/local_only-zh-Hans
  spec/fixtures/mock_responses/localelist
  spec/fixtures/mock_responses/nonexistent
  spec/loader/available_bundles_spec.rb
  spec/loader/mix_spec.rb
  spec/spec_helper.rb
  spec/support/helpers.rb
  spec/support/logger_helper.rb
  spec/support/shared_examples_for_available_bundles.rb
  spec/unit/cache_spec.rb
  spec/unit/config_spec.rb
  spec/unit/locale_spec.rb
Labels: cla-not-required, priority/high, area/ruby-client

#1623 define new interfaces
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/util/locale-util.rb
  lib/singleton-client.rb
  singleton-ruby.gemspec
  spec/fixtures/bundles/test/4.8.1/JAVA/messages_de.json
  spec/fixtures/bundles/test/4.8.1/JAVA/messages_en.json
  spec/fixtures/bundles/test/4.8.1/JAVA/messages_latest.json
  spec/fixtures/bundles/test/4.8.1/JAVA/messages_zh-Hans.json
  spec/fixtures/bundles/test/4.8.1/JAVA/messages_zh-Hant.json
  spec/fixtures/bundles/test/4.8.1/creation.json
  spec/fixtures/bundles/test/4.8.1/local_only/messages_en.json
  spec/fixtures/bundles/test/4.8.1/local_only/messages_zh-Hans.json
  spec/fixtures/bundles/test/4.8.1/version.json
  spec/fixtures/sources/JAVA/default.yml
  spec/fixtures/sources/NEW/default.yml
  spec/fixtures/sources/NEW/new.yml
  spec/singleton_spec.rb
  spec/spec_helper.rb
  spec/support/helpers.rb
  spec/support/shared_contexts.rb
  spec/unit/config_spec.rb
  spec/unit/locale_spec.rb
  spec/unit/logging_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
Labels: cla-not-required, area/ruby-client

#1665 improve new interfaces
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/sgtn-client.rb
  lib/singleton-client.rb
  spec/singleton_spec.rb
  spec/spec_helper.rb
Labels: cla-not-required

#1673 change parameters of key interface
  lib/sgtn-client/api/translation.rb
  spec/singleton_spec.rb
Labels: cla-not-required

#1664 throw exceptions when errors happen
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/loader/cache.rb
  lib/sgtn-client/loader/chain_loader.rb
  lib/sgtn-client/loader/loader_factory.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/single_loader.rb
  lib/sgtn-client/loader/source.rb
  lib/sgtn-client/loader/source_comparer.rb
  spec/fixtures/mock_responses/business_error_601
  spec/fixtures/mock_responses/business_error_701
  spec/loader/mix_spec.rb
Labels: cla-not-required, area/ruby-client

#1601 add gradle doc task
  g11n-ws/tools/tool-cldr-extractor/build.gradle
Labels: cla-not-required

#1423 [Copyright] Update Singleton pattern library copyright year to 2022
  build.gradle
  settings.gradle
  src/main/java/com/vmware/i18n/PatternConfig.java
  src/main/java/com/vmware/i18n/PatternParseMain.java
  src/main/java/com/vmware/i18n/PatternUtil.java
  src/main/java/com/vmware/i18n/cldr/CLDR.java
  src/main/java/com/vmware/i18n/common/CLDRConstants.java
  src/main/java/com/vmware/i18n/common/Constants.java
  src/main/java/com/vmware/i18n/common/DayEnum.java
  src/main/java/com/vmware/i18n/common/OfficialStatusEnum.java
  src/main/java/com/vmware/i18n/dto/LocaleDataDTO.java
  src/main/java/com/vmware/i18n/locale/action/LocaleAction.java
  src/main/java/com/vmware/i18n/locale/dao/ILocaleDao.java
  src/main/java/com/vmware/i18n/locale/dao/impl/LocaleDaoImpl.java
  src/main/java/com/vmware/i18n/locale/service/ILocaleService.java
  src/main/java/com/vmware/i18n/locale/service/impl/LocaleServiceImpl.java
  src/main/java/com/vmware/i18n/pattern/action/PatternAction.java
  src/main/java/com/vmware/i18n/pattern/dao/IPatternDao.java
  src/main/java/com/vmware/i18n/pattern/dao/impl/PatternDaoImpl.java
  src/main/java/com/vmware/i18n/pattern/service/IPatternService.java
  src/main/java/com/vmware/i18n/pattern/service/impl/PatternServiceImpl.java
  src/main/java/com/vmware/i18n/utils/CLDRUtils.java
  src/main/java/com/vmware/i18n/utils/CommonUtil.java
  src/main/java/com/vmware/i18n/utils/IOUtil.java
  src/main/java/com/vmware/i18n/utils/JSONUtil.java
  src/main/java/com/vmware/i18n/utils/LocalJSONReader.java
  src/main/java/com/vmware/i18n/utils/LocaleDataUtils.java
  src/main/java/com/vmware/i18n/utils/MiscUtils.java
  src/main/java/com/vmware/i18n/utils/PathUtils.java
  src/main/java/com/vmware/i18n/utils/PropertiesFileUtil.java
  src/main/java/com/vmware/i18n/utils/SupplementUtils.java
  src/main/java/com/vmware/i18n/utils/timezone/CldrTimeZoneUtils.java
  src/main/java/com/vmware/i18n/utils/timezone/TimeZoneDisplayName.java
  src/main/java/com/vmware/i18n/utils/timezone/TimeZoneName.java
  src/test/java/com/vmware/i18n/PatternParseMainTest.java
  src/test/java/com/vmware/i18n/PatternUtilTest.java
  src/test/java/com/vmware/test/i18n/I18nUtilTest.java
Labels: cla-not-required, area/cldr-pattern

#1442 Upgrade commons-io to latest version 2.11.0
  build.gradle
Labels: cla-not-required, area/cldr-pattern

#1674 update README and sample application
  README.md
  lib/sgtn-client/loader/local_translation.rb
  samples/Gemfile
  samples/Gemfile.lock
  samples/README.md
  samples/app.rb
  samples/config/locales/default/JAVA/default.yml
  samples/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_en.json
  samples/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_latest.json
  samples/config/locales/l10n/bundles/test/4.8.1/JAVA/messages_zh-Hans.json
  samples/config/sgtnclient.yml
  samples/formatting/all.rb
  samples/runner.rb
  samples/translation/all.rb
  spec/config/sgtnclient-invalidate.yml
  spec/config/sgtnclient.yml
Labels: cla-not-required, area/ruby-client
