Repository vmware/singleton, pull requests merged in 2022-10, with the labels that each got.

#1906 raise when errors happen
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/fallbacks.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/locale-util.rb
  lib/singleton-client.rb
  spec/autoload_spec.rb
  spec/fallbacks_spec.rb
  spec/loader/mix_spec.rb
  spec/loader/single_loader_spec.rb
  spec/raise_error_spec.rb
  spec/singleton_spec.rb
  spec/support/helpers.rb
  spec/support/shared_contexts.rb
  spec/support/shared_examples_for_available_bundles.rb
  spec/support/utils.rb
  spec/unit/cache_spec.rb
  spec/unit/config_spec.rb
  spec/unit/inconfig_spec.rb
  spec/unit/offclient_spec.rb
  spec/unit/onclient_spec.rb
  spec/unit/plural_spec.rb
  spec/unit/request_spec.rb
Labels: cla-not-required, area/ruby-client

#1914 fix test erros and #1913
  api/v2/swagger/docs.go
  api/v2/swagger/swagger.json
  api/v2/swagger/swagger.yaml
  api/v2/translation/handler_trans.go
  api/v2/translation/types_trans.go
  tests/healthcheck_test.go
  tests/pseudo_test.go
Labels: cla-not-required, area/go-service

#1884 Update codecov.yml to fit configure format change
  codecov.yml
Labels: cla-not-required

#1885 Update codecov.yml to fit configure format change
  codecov.yml
Labels: cla-not-required

#1886 Update codecov.yml to fit configure format change
  .github/workflows/node.js.yml
  codecov.yml
Labels: cla-not-required

#1908 Add translation bind single version in saas singleton
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/utils/VersionMatcher.java
Labels: cla-not-required

#1923 fix security issue 1921: remove unused dependency jackson-databind
  build.gradle
Labels: cla-not-required, area/java-client

#1922 fix 1921-[Security][cldr-pattern]: Upgrade jackson-databind to latest version (2.13.4.2)
  build.gradle
Labels: cla-not-required, area/cldr-pattern
