Repository vmware/singleton, pull requests merged in 2022-09, with the labels that each got.

#1863 Imporve axios version to follow peerDependencies ecosystem standard
  package.client.json
  package.json
Labels: cla-not-required

#1865 fixed the components v1 api s3 storage error msg
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v1/translation/TranslationComponentAPI.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v1/translation/TranslationProductComponentAPI.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsMsg.java
Labels: cla-not-required

#1872 support pseudo translation
  api/v1/swagger/docs.go
  api/v1/swagger/swagger.json
  api/v1/swagger/swagger.yaml
  api/v1/translation/handler_trans.go
  api/v1/translation/types_trans.go
  api/v2/combine/handler_combine.go
  api/v2/combine/types_combine.go
  api/v2/swagger/docs.go
  api/v2/swagger/swagger.json
  api/v2/swagger/swagger.yaml
  api/v2/translation/handler_trans.go
  api/v2/translation/types_trans.go
  modules/translation/interfaces.go
  modules/translation/translationservice/pseudo_service.go
  modules/translation/translationservice/trans_service.go
  modules/translation/types.go
  tests/pseudo_test.go
Labels: cla-not-required, area/go-service

#1873 add l10n support slash in url
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/WebConfiguration.java
Labels: cla-not-required

#1876 add health-check actuator
  api/actuator/actuator.go
  cmd/singleton/main.go
  go.mod
  go.sum
  tests/healthcheck_test.go
Labels: cla-not-required, area/go-service

#1881 change response HTTP code to 200
  api/utils.go
  tests/api_test.go
  tests/cldr_api_test.go
  tests/combine_api_test.go
  tests/trans_api_test.go
Labels: cla-not-required, area/go-service

#1874 upgrade the snakeyaml jar
  g11n-ws/build.gradle
Labels: cla-not-required

#1883 remove httpclient5 dependency jar
  g11n-ws/modules/md-service-authen/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
Labels: cla-not-required

#1892 upgrade sqlite-jdbc
  g11n-ws/build.gradle
Labels: cla-not-required

#1889 change response code 207 to 200 for combine API to adapt JS client
  api/v2/combine/handler_combine.go
  tests/combine_api_test.go
Labels: cla-not-required, area/go-service

#1903 set status for getting pseudo string correctly to fix #1900
  modules/translation/status.go
  modules/translation/translationservice/pseudo_service.go
Labels: cla-not-required, area/go-service

#1899 process multiple errors for getting multiple bundles to fix #1890 and #1898
  api/v2/translation/handler_trans.go
  modules/translation/translationservice/pseudo_service.go
  modules/translation/translationservice/trans_service.go
  tests/api_test.go
  tests/cldr_api_test.go
Labels: cla-not-required, area/go-service

#1896 change type of pseudo in combine post API to string to fix #1894
  api/v2/combine/handler_combine.go
  api/v2/combine/types_combine.go
  api/v2/swagger/docs.go
  api/v2/swagger/swagger.json
  api/v2/swagger/swagger.yaml
Labels: cla-not-required, area/go-service

#1895 add configuration to enable/disable allow list
  api/v2/translation/middlewares.go
  config/config_template.yaml
  internal/config/config.go
  tests/api_test.go
  tests/testdata/config/config.yaml
Labels: cla-not-required, area/go-service

#1879 set default cache expiration to 24 hours
  lib/sgtn-client/common/data.rb
  spec/unit/cache_spec.rb
Labels: cla-not-required, area/ruby-client
