Repository vmware/singleton, pull requests merged in 2022-05, with the labels that each got.

#1683 change module name from Singleton to Sgtn
  README.md
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/cldr/localized_str.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/source.rb
  lib/singleton-client.rb
  samples/README.md
  samples/translation/all.rb
  spec/loader/mix_spec.rb
  spec/singleton_spec.rb
  spec/spec_helper.rb
  spec/support/utils.rb
Labels: cla-not-required, area/ruby-client

#1689 Update GitHub Actions for G11n ruby client to correct unit test scope
  .github/workflows/main.yml
Labels: cla-not-required

#1669 update the detail error msg
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
Labels: cla-not-required

#1697 remove finished thread only once
  lib/sgtn-client/loader/single_loader.rb
Labels: kind/bug, cla-not-required, area/ruby-client

#1700 Revert "Update GitHub Action for g11n-js-client to fix unit test coverage not uploaded to codecov issue" to reduce useless commit
  .github/workflows/node.js.yml
Labels: cla-not-required

#1705 Upgrade tomcat
  g11n-ws/build.gradle
Labels: cla-not-required

#1699 improve locale utility to fix #1691 and #1694
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/util/locale-util.rb
  spec/spec_helper.rb
  spec/unit/config_spec.rb
  spec/unit/locale_spec.rb
Labels: cla-not-required, area/ruby-client

#1712 speed up loading source
  lib/sgtn-client/loader/source.rb
  singleton-ruby.gemspec
Labels: cla-not-required, area/ruby-client

#1704 Improve collect-source-bundle CLI script in support of transforming ECMAScript modules to CommonJS
  cli/collect-source-bundle.js
  package.client.json
  package.json
  src/constants.ts
Labels: cla-not-required

#1721 fix #1719 NameError: uninitialized constant SgtnClient::StringUtil
  lib/sgtn-client/sgtn-client.rb
Labels: cla-not-required
