Repository vmware/singleton, pull requests merged in 2022-01, with the labels that each got.

#1409 add sync for thread-safe and fix bug for ruby v2.3.3 version
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/file-util.rb
Labels: cla-not-required

#1419 [Go-Client]change headers to 2022
  bundle_dao.go
  bundle_test.go
  cache_default.go
  cache_info.go
  cache_interface.go
  cache_service.go
  cache_test.go
  common.go
  config.go
  config_test.go
  consts.go
  data_default.go
  data_test.go
  httpclient.go
  httpclient_test.go
  inst.go
  inst_test.go
  logger_default.go
  logger_test.go
  messages.go
  server_dao.go
  server_test.go
  testutil_test.go
  translation.go
  translation_interface.go
  translation_manager.go
  translation_test.go
Labels: cla-not-required

#1433 Update build.gradle for Singleton i18n service autotest and l10n service autotest project due to springboot upgrade
  autotest/service/i18n-service/APITest/build.gradle
  autotest/service/l10n-service/APITest/build.gradle
Labels: cla-not-required

#1435 change the requested component name
  autotest/client/java/src/main/java/com/vmware/vip/test/javaclient/httprequester/CustomizeHeader.java
Labels: cla-not-required

#1438 upgrade the gradle scripts
  autotest/service/i18n-service/APITest/build.gradle
  autotest/service/l10n-service/APITest/build.gradle
Labels: cla-not-required

#1432 [i18n-manager] change parameter source to optional in string-based api
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v1/translation/TranslationProductComponentKeyAPI.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductComponentKeyAPI.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/string/StringService.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsMsg.java
Labels: cla-not-required, area/java-service, kind/feature, priority/high

#1444 [Singleton ruby client] avoid request for non-existing component
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/request.rb
  spec/config/locales/default/NEW/default.yml
  spec/unit/onclient_spec.rb
Labels: cla-not-required, area/ruby-client

#1447 fix UT failed issue: https://github.com/vmware/singleton/issues/1446
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/string/StringService.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/ConstantsForTest.java
  g11n-ws/vip-manager-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationSyncAPITest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/common/ConstantsForTest.java
  g11n-ws/vip-manager-lite-i18n/src/test/java/com/vmware/vip/i18n/api/v1/translation/TranslationSyncAPITest.java
Labels: cla-not-required

#1427 restructure the update source to local and remote
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/ServerShutdownListener.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/crons/SourceCollectCacheCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/crons/SourceLocalBundleCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/crons/SourceSendGRMCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/crons/SourceSendI18nCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/crons/SourceSendingCron.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/SourceService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/SyncGrmSourceService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/SyncI18nSourceService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/SyncLocalBundleService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SourceServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SyncGrmSourceServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SyncI18nSourceServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SyncLocalBundleServiceImpl.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/DiskQueueUtils.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/utils/SourceCacheUtils.java
  g11n-ws/vip-manager-l10n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-l10n/src/main/resources/bundle.json
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/SourceDaoTest.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/controller/SourceSendingCronTest.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/l10n/source/service/SourceServiceTest.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/l10n/source/service/TestSyncGrmSourceService.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/l10n/source/service/TestSyncI18nSourceService.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/l10n/source/service/TestSyncLocalBundleService.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/l10n/utils/TestDiskQueueUtils.java
  g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestModels.java
Labels: cla-not-required

#1454 Change the execution order of cases to avoid interfering with testing
  autotest/client/ruby/spec/Config_spec.rb
Labels: cla-not-required

#1458 [Ruby client] change the cache's global variables to classic
  lib/sgtn-client/core/cache.rb
Labels: cla-not-required

#1459 update the jars and reorder maven repo url
  g11n-ws/build.gradle
Labels: cla-not-required

#1461 [Ruby client] add cache for unsuppported languages to avoid request
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/config.rb
  lib/sgtn-client/util/cache-util.rb
  spec/config/sgtnclient.yml
  spec/unit/cache_spec.rb
  spec/unit/onclient_spec.rb
Labels: cla-not-required

#1466 [Ruby client] improve performance on cache invalidate
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/util/cache-util.rb
  spec/config/sgtnclient.yml
  spec/unit/onclient_spec.rb
Labels: cla-not-required

#1467 [G11n ruby client]improve empty check and unit test
  lib/sgtn-client/api/translation.rb
  spec/config/sgtnclient.yml
  spec/unit/onclient_spec.rb
Labels: cla-not-required

#1470 [ruby client] add check to write cache
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/util/cache-util.rb
Labels: cla-not-required

#1471 Update test case，because field default_language be added in config.yml
  autotest/client/ruby/Gemfile
  autotest/client/ruby/config/sgtnclient.yml
  autotest/client/ruby/spec/Cache_spec.rb
  autotest/client/ruby/spec/Default_cache_spec.rb
  autotest/client/ruby/spec/SimpleT_offline_spec.rb
  autotest/client/ruby/spec/SimpleT_spec .rb
  autotest/client/ruby/spec/Translation_offline_spec.rb
  autotest/client/ruby/spec/Translation_spec.rb
Labels: cla-not-required

#1464 Update get-commit-range-action to fix bug
  .github/actions/get-commit-range-action/action.yml
Labels: cla-not-required

#1404 Update GitHub Action for g11n-js-client to fix unit test coverage not uploaded to codecov issue
  .github/workflows/node.js.yml
Labels: cla-not-required

#1472 [Ruby client]improve log and unit test
  lib/sgtn-client/api/source.rb
  lib/sgtn-client/api/translation.rb
  lib/sgtn-client/core/cache.rb
  lib/sgtn-client/core/request.rb
  lib/sgtn-client/sgtn-client.rb
  lib/sgtn-client/util/cache-util.rb
  lib/sgtn-client/util/file-util.rb
  lib/sgtn-client/util/validate-util.rb
  spec/spec_helper.rb
  spec/unit/cache_spec.rb
  spec/unit/datetime_spec.rb
Labels: cla-not-required
