Repository vmware/singleton, pull requests merged in 2022-12, with the labels that each got.

#1987 add interactive scenario with java client in CLDR smoke testing
  autotest/cldrpattern/ExtractedPatternLibTestCases.xlsx
  autotest/cldrpattern/constant.py
  autotest/cldrpattern/java-client-sample/README.md
  autotest/cldrpattern/java-client-sample/build.gradle
  autotest/cldrpattern/java-client-sample/gradle/wrapper/gradle-wrapper.jar
  autotest/cldrpattern/java-client-sample/gradle/wrapper/gradle-wrapper.properties
  autotest/cldrpattern/java-client-sample/gradlew
  autotest/cldrpattern/java-client-sample/gradlew.bat
  autotest/cldrpattern/java-client-sample/settings.gradle
  autotest/cldrpattern/java-client-sample/src/main/java/com/vmware/vipclient/sample/Format.java
  autotest/cldrpattern/java-client-sample/src/main/java/com/vmware/vipclient/sample/Format2.java
  autotest/cldrpattern/java-client-sample/src/main/java/com/vmware/vipclient/sample/Main.java
  autotest/cldrpattern/java-client-sample/src/main/java/com/vmware/vipclient/sample/Translation.java
  autotest/cldrpattern/java-client-sample/src/main/java/com/vmware/vipclient/sample/TranslationDemo.java
  autotest/cldrpattern/java-client-sample/src/main/resources/log4j.properties
  autotest/cldrpattern/java-client-sample/src/main/resources/messages.properties
  autotest/cldrpattern/java-client-sample/src/main/resources/offlineBundles/default/messages_en.json
  autotest/cldrpattern/java-client-sample/src/main/resources/offlineBundles/default/messages_fil.json
  autotest/cldrpattern/java-client-sample/src/main/resources/offlineBundles/default/messages_fr.json
  autotest/cldrpattern/java-client-sample/src/main/resources/offlineBundles/default/messages_source.json
  autotest/cldrpattern/java-client-sample/src/main/resources/sampleconfig.properties
  autotest/cldrpattern/test.py
Labels: cla-not-required

#1983 add license header to makefile
  Makefile
Labels: cla-not-required, area/go-service

#1986 write ETag case-sensitively to fix #1943
  api/cchandler.go
  tests/api_test.go
  tests/trans_api_test.go
Labels: cla-not-required, area/go-service

#1991 update the log4j2 configuration
  g11n-ws/vip-manager-i18n/src/main/resources/log4j2-spring.xml
  g11n-ws/vip-manager-l10n/src/main/resources/log4j2-spring.xml
  g11n-ws/vip-manager-lite-i18n/src/main/resources/log4j2-spring.xml
Labels: cla-not-required

#1999 Add the older log file auto delete Strategy
  g11n-ws/vip-manager-i18n/src/main/resources/log4j2-spring.xml
  g11n-ws/vip-manager-l10n-agent/src/main/resources/log4j2-spring.xml
  g11n-ws/vip-manager-l10n/src/main/resources/log4j2-spring.xml
  g11n-ws/vip-manager-lite-i18n/src/main/resources/log4j2-spring.xml
Labels: cla-not-required

#2003 [Devops][Ruby client]update smoke test code with the Sgtn.get_translations() change
  autotest/client/ruby/spec/mixd/Translation_get_translations_spec.rb
  autotest/client/ruby/spec/offline/Translation_get_translations_spec.rb
  autotest/client/ruby/spec/online/Translation_get_translations_spec.rb
  autotest/client/ruby/spec/online/Translation_translate_spec.rb
  autotest/client/ruby/spec/onlineandoffline/Translation_get_translations_spec.rb
  autotest/client/ruby/spec/onlyoffline/Translation_get_translations_spec.rb
  autotest/client/ruby/spec/onlyoffline/Translation_translate_spec.rb
  autotest/client/ruby/spec/onlyserver/Translation_get_translations_spec.rb
  autotest/client/ruby/spec/onlysource/Translation_get_translations_spec.rb
Labels: cla-not-required, area/devops

#2001 Set pattern to latest version
  g11n-ws/modules/md-service-i18n-l2/build.gradle
Labels: cla-not-required

#2005 read from storage again if time is out to wait for cache
  internal/cache/cache_interface.go
  internal/common/utils.go
  modules/cldr/localeutil/cache/localecache.go
  modules/translation/translationcache/transcache.go
  tests/common_test.go
  tests/trans_test.go
Labels: cla-not-required, area/go-service
