Repository vmware/singleton, pull requests merged in 2023-02, with the labels that each got.

#2066 Remove some outdated test case and update the versions of same depend…
  autotest/client/ruby/Gemfile
  autotest/client/ruby/spec/mixd/Translation_translate_spec.rb
  autotest/client/ruby/spec/offline/Translation_translate_spec.rb
  autotest/client/ruby/spec/online/Translation_translate_spec.rb
  autotest/client/ruby/spec/onlineandoffline/Translation_translate_spec.rb
  autotest/client/ruby/spec/onlyoffline/Translation_translate_spec.rb
  autotest/client/ruby/spec/onlyserver/Translation_translate_spec.rb
  autotest/client/ruby/spec/onlysource/Translation_translate_spec.rb
Labels: cla-not-required, area/devops

#2067 [cldr pattern]update the root path of zip files in smoke testing.
  autotest/cldrpattern/constant.py
Labels: cla-not-required

#2068 [cldr pattern]update the test data since timezone is different in CI machine.
  autotest/cldrpattern/ExtractedPatternLibTestCases.xlsx
Labels: cla-not-required

#2069 [cldr pattern]Update script
  autotest/cldrpattern/test.py
Labels: cla-not-required

#1995 upgrade source code compatibility JDK11
  g11n-ws/modules/md-data-api-mt/build.gradle
  g11n-ws/modules/md-data-api-s3impl/build.gradle
  g11n-ws/modules/md-service-i18n-l2/build.gradle
  g11n-ws/modules/md-service-i18n-l3/build.gradle
  g11n-ws/vip-common/build.gradle
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/LocaleUtils.java
Labels: cla-not-required

#1755 improve product API performance
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/FileComponentChannelDao.java
  g11n-ws/modules/md-data-api-pgimpl/src/main/java/com/vmware/vip/messages/data/dao/pgimpl/PgComponentChannelDao.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3ComponentChannelDao.java
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3OneComponentDaoImpl.java
  g11n-ws/modules/md-data-api/src/main/java/com/vmware/vip/messages/data/dao/api/IComponentChannelDao.java
  g11n-ws/modules/md-data-api/src/main/java/com/vmware/vip/messages/data/dao/model/ResultMessageChannel.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/StreamProductAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/StreamProductResp.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductAction.java
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationProductAPI.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/multcomponent/IMultComponentService.java
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/multcomponent/MultComponentService.java
Labels: cla-not-required

#2058 add i18n key set base64 soruce format validate
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/TranslationProductComponentKeyAction.java
Labels: cla-not-required

#2070 upgrade sqlite dependency jar
  g11n-ws/build.gradle
Labels: cla-not-required

#2072 upgrade web dependency jars
  g11n-ws/build.gradle
Labels: cla-not-required

#2059 Update GitHub Actions to update smoke test
  .github/workflows/gradle.yml
Labels: cla-not-required

#2061 fixed the put token validate error
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationSyncAPI.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/auth/interceptor/AuthInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/service/impl/SyncI18nSourceServiceImpl.java
Labels: cla-not-required

#2074 Add performance testing to GitHub Actions CI
  .github/workflows/main.yml
Labels: cla-not-required

#1997 fix bug 1990: Avoid ERROR log for non-exist supplemental file
  src/main/java/com/vmware/i18n/pattern/service/impl/PatternServiceImpl.java
Labels: cla-not-required

#2076 Update codecov configure to fit latest format
  codecov.yml
Labels: cla-not-required

#2080 Update GitHub Actions to integrate codacy check, update codecov configure and fix coverage not correct issue
  .github/workflows/main.yml
Labels: cla-not-required

#2082 Update unit test patch coverage configure
  codecov.yml
Labels: cla-not-required

#2081 add pseudo in product stream API
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/StreamProductAction.java
Labels: cla-not-required

#2085 remove Sensitive configuration items
  g11n-ws/vip-manager-i18n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-i18n/src/main/resources/application-s3.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
Labels: cla-not-required

#2083 process the sourceformat to upper
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/SourceController.java
Labels: cla-not-required

#2086 add the validation of the l10n Agent
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/SingleComponentServiceImpl.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/utils/ResouceFileUtils.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/utils/ValidationUtils.java
  g11n-ws/vip-manager-l10n-agent/src/main/resources/log4j2-spring.xml
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/service/RecordServiceImpl.java
Labels: cla-not-required

#2073 support source
  bundle_dao.go
  bundle_test.go
  cache_info.go
  cache_service.go
  cache_test.go
  common.go
  config.go
  consts.go
  data_default.go
  data_test.go
  go.mod
  go.sum
  httpclient.go
  inst.go
  inst_test.go
  messages.go
  mix_test.go
  origin_chain.go
  server_dao.go
  server_test.go
  single_loader.go
  single_loader_test.go
  source_as_origin.go
  source_comparison.go
  source_comparison_test.go
  source_in_translation.go
  source_interface.go
  source_local.go
  source_registration.go
  source_registration_test.go
  testdata/bundles/SgtnTest/1.0.0/sunglow/messages_latest.json
  testdata/bundles/SgtnTest/1.0.0/users/messages_latest.json
  testdata/conf/config.json
  testdata/mock/__files/componentMessages-en-sunglow.json
  testdata/mock/__files/componentMessages-en-users.json
  testdata/mock/__files/componentMessages-latest-sunglow.json
  testdata/mock/__files/componentMessages-latest-users.json
  testdata/mock/__files/componentMessages-versionfallback.json
  testdata/mock/__files/localelist.json
  testdata/mock/__files/localelist_secondtime.json
  testdata/mock/mappings/componentMessages.json
  testdata/sources/SgtnTest/1.0.0/sunglow/messages.json
  testdata/sources/SgtnTest/1.0.0/users/messages.json
  testutil_test.go
  translation.go
  translation_test.go
Labels: cla-not-required, area/go-client

#2018 add l10n manager request log interceptor
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/WebConfiguration.java
  g11n-ws/vip-manager-l10n/src/main/resources/application-bundle.properties
  g11n-ws/vip-manager-l10n/src/main/resources/application-s3.properties
Labels: cla-not-required

#2096 remove apace in component list
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3ProductDaoImpl.java
Labels: cla-not-required

#2095 fixed the only have version object in s3 return 520
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/dao/impl/S3ProductDaoImpl.java
Labels: cla-not-required

#2098 get locale list of a release than all releases in local bundle
  bundle_dao.go
Labels: cla-not-required, area/go-client

#2103 add pesudo exception when latest source not found
  g11n-ws/modules/md-service-i18n-l3/src/main/java/com/vmware/vip/core/messages/service/multcomponent/MultComponentService.java
Labels: cla-not-required

#2105 Csptoken check the claim item is null for compatible all clients token
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/csp/service/CSPTokenService.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CspAuthInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CspValidateService.java
Labels: cla-not-required

#2091 add custom singleton service log configuration
  content/en/docs/overview/singleton-service/singleton-service-custom-log.md
Labels: cla-not-required

#2100 support local source
  bundle_dao.go
  bundle_test.go
  cache_test.go
  config.go
  data_test.go
  go.mod
  go.sum
  inst.go
  messages.go
  origin_chain.go
  origin_chain_test.go
  server_dao.go
  single_loader_test.go
  source_as_origin_test.go
  source_comparison.go
  source_comparison_test.go
  source_in_translation.go
  source_in_translation_test.go
  source_local.go
  source_local_test.go
  source_registration_test.go
  testdata/bundles/SgtnTest/1.0.0/sunglow/messages_latest.json
  testdata/conf/config.json
  testdata/sources/SgtnTest/1.0.0/sunglow/messages_en.json
  testdata/sources/SgtnTest/1.0.0/users/messages_en.json
  testutil_test.go
  translation_test.go
Labels: cla-not-required, area/go-client, priority/medium
