Repository vmware/singleton, pull requests merged in 2023-01, with the labels that each got.

#2036 To be compatible with Ruby 2.3
  .rubocop.yml
  lib/sgtn-client/fallbacks.rb
  singleton-client.gemspec
Labels: cla-not-required, area/ruby-client

#2017 source should be collected successfully when csp token setting true
  g11n-ws/modules/md-data-api-s3impl/build.gradle
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/v2/translation/TranslationSyncAPI.java
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/auth/interceptor/AuthInterceptor.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsKeys.java
Labels: cla-not-required

#2019 fix the l10n log configuration
  g11n-ws/vip-manager-l10n/src/main/resources/log4j2-spring.xml
Labels: cla-not-required

#2020 fixed the bundle API only have version directory action
  g11n-ws/modules/md-data-api-bundleimpl/src/main/java/com/vmware/vip/messages/data/dao/impl/ProductDao.java
Labels: cla-not-required

#2041 add base64 decode in l10n api
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ConstantsKeys.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/SourceFormatUtils.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/conf/CollectSourceValidationInterceptor.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/SourceController.java
  g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/controller/TranslationCollectKeyAPI.java
Labels: cla-not-required

#2044 use Pathname.glob and unuse Hash.transform_values! to be compatible with Ruby 2.3
  lib/sgtn-client/fallbacks.rb
  lib/sgtn-client/loader/local_translation.rb
  lib/sgtn-client/loader/pseudo.rb
  lib/sgtn-client/loader/source.rb
Labels: cla-not-required, area/ruby-client

#2042 add multiple components interface
  bundle_dao.go
  common.go
  consts.go
  data_default.go
  go.sum
  server_dao.go
  testdata/mock/__files/componentMessages-RefreshCache-sunglow.json
  testdata/mock/__files/componentMessages-RefreshCacheSecondTime-sunglow.json
  testdata/mock/__files/componentMessages-en-US-sunglow.json
  testdata/mock/__files/componentMessages-en-US-users.json
  testdata/mock/__files/componentMessages-fr-sunglow.json
  testdata/mock/__files/componentMessages-fr-users.json
  testdata/mock/__files/componentMessages-versionfallback.json
  testdata/mock/__files/componentMessages-zh-Hans-HTTP404.json
  testdata/mock/__files/componentMessages-zh-Hans-WrongResponseContent.json
  testdata/mock/__files/componentMessages-zh-Hans-sunglow-decodeerror.json
  testdata/mock/__files/componentMessages-zh-Hans-sunglow-pseudo.json
  testdata/mock/__files/componentMessages-zh-Hans-sunglow.json
  testdata/mock/__files/componentMessages-zh-Hans-users.json
  testdata/mock/mappings/componentMessages.json
  testdata/mock/mappings/componentlist.json
  testdata/mock/mappings/localelist.json
  translation.go
  translation_interface.go
  translation_test.go
Labels: cla-not-required, area/go-client

#2062 change type of 'pseudo' field in POST combine interface to fix #2035
  api/v2/combine/handler_combine.go
  api/v2/combine/types_combine.go
Labels: cla-not-required, area/go-service

#2063 remove version limit on dependent libs and update sample
  samples/Gemfile
  samples/Gemfile.lock
  samples/app.rb
  samples/config/locales/default/JAVA/default.yml
  samples/config/sgtnclient.yml
  samples/translation/all.rb
  singleton-client.gemspec
Labels: cla-not-required, area/ruby-client
