Repository vmware/singleton, pull requests merged in 2023-03, with the labels that each got.

#2108 remove fatal error message
  g11n-ws/modules/md-service-about/src/main/java/com/vmware/vip/core/about/service/version/VersionService.java
Labels: cla-not-required

#2112 upgrade common-upload
  g11n-ws/modules/md-service-authen/build.gradle
Labels: cla-not-required

#2111 support source locale as 2nd fallback
  common.go
  config.go
  data_test.go
  inst.go
  inst_test.go
  locale_fallback_test.go
  messages.go
  single_loader_test.go
  source_as_origin.go
  source_comparison.go
  source_comparison_test.go
  source_in_translation.go
  source_in_translation_test.go
  source_local.go
  source_local_test.go
  source_registration_test.go
  testutil_test.go
  translation.go
  translation_manager.go
  translation_test.go
Labels: cla-not-required, area/go-client, priority/medium

#2107 Adding CI to the python client side of Singleton Project.
  .github/actions/get-branch-name-action/action.yml
  .github/actions/get-commit-range-action/action.yml
  .github/actions/were-only-docs-updated-action/action.yml
  .github/workflows/main.yml
Labels: cla-not-required

#2114 improve unit tests coverage
  api/server.go
  cmd/singleton/main.go
  internal/common/utils.go
  tests/server_test.go
  tests/testdata/config/config.yaml
  tests/testdata/https/server.key
  tests/testdata/https/server.pem
  tests/testutils_test.go
  tests/trans_test.go
Labels: cla-not-required, area/go-service

#2116 upgrade the readme index
  README.md
  content/en/docs/overview/singleton-service/singleton-service-custom-log.md
Labels: cla-not-required

#2121 Update codecov configure to fit latest format and integrate codacy static analysis into gitHub acitons CI
  .github/workflows/main.yml
  codecov.yml
Labels: cla-not-required

#2089 fix bug 1436: [BUG] [CLDR pattern] CLDR pattern lib can't be compiled with JDK11.
  src/main/java/com/vmware/i18n/utils/CommonUtil.java
Labels: cla-not-required

#2120 add the user-agent header
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/base/PropertyContantKeys.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/conf/PropertyConfigs.java
  g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/RecordServiceImpl.java
  g11n-ws/vip-manager-l10n-agent/src/main/resources/application.properties
Labels: cla-not-required

#2088 fix bug 1949: [BUG][Java Client]Return null when corresponding data in response is null with get multiple components interface.
  src/main/java/com/vmware/vipclient/i18n/common/ConstantsMsg.java
  src/main/java/com/vmware/vipclient/i18n/messages/api/opt/server/ComponentsBasedOpt.java
  src/main/java/com/vmware/vipclient/i18n/messages/service/ComponentsService.java
  src/test/java/com/vmware/vip/i18n/TranslationMessageTest.java
  src/test/resources/mockserver/mappings/mapping-i18n-api-v2-translation-products-JavaclientTest-versions-1.0.0.json
Labels: cla-not-required

#2102 [JSCLient]Improve CLI Script on adding encoding source string feature.
  cli/collect-source-bundle.js
  cli/translation-service.js
  package.client.json
  package.json
Labels: cla-not-required

#2129 query locales from both translation and source
  bundle_test.go
  inst.go
  origin_chain.go
  server_test.go
  source_comparison.go
  source_comparison_test.go
  source_in_translation.go
  source_locale_verification.go
  translation_test.go
Labels: cla-not-required, area/go-client

#2130 upgrade sqllite jar
  g11n-ws/build.gradle
Labels: cla-not-required

#2131 Add dependabot configure to the repo
  .github/dependabot.yml
Labels: cla-not-required

#2182 skip testcase cache online
  autotest/client/python/main/testcases/cache/test_cache_online.py
Labels: cla-not-required

#2184 upgrade spring boot
  g11n-ws/build.gradle
Labels: cla-not-required

#2179 fixed build java11 run openjdk8 issue
  g11n-ws/modules/md-restful-api-i18n/src/main/java/com/vmware/vip/i18n/api/base/StreamProductAction.java
Labels: cla-not-required

#2186 bug fix for https://jira.eng.vmware.com/browse/RED-4164
  g11n-ws/modules/md-service-authen/src/main/java/com/vmware/vip/core/validation/ParameterValidation.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/constants/ValidationMsg.java
  g11n-ws/vip-common/src/main/java/com/vmware/vip/common/utils/RegExpValidatorUtils.java
Labels: cla-not-required

#2188 upgrade yaml jar
  g11n-ws/build.gradle
Labels: cla-not-required

#2195 upgrade tomcat
  g11n-ws/build.gradle
Labels: cla-not-required

#2189 Fixed the part translation response json
  g11n-ws/modules/md-data-api/src/main/java/com/vmware/vip/messages/data/dao/model/ResultMessageChannel.java
Labels: cla-not-required

#2196 [cldr pattern]add file directory structure check in smoke testing
  autotest/cldrpattern/ExtractedPatternLibTestCases.xlsx
  autotest/cldrpattern/constant.py
  autotest/cldrpattern/excelutility.py
  autotest/cldrpattern/test.py
Labels: cla-not-required
