Repository vmware/singleton, pull requests merged in 2024-03, with the labels that each got.

#3050 fix 2693: Improve document for usage of getMultiVersionKeyMessage API
  content/en/docs/overview/singleton-sdk/resources/java-client/0.6.3/javadoc/com/vmware/vipclient/i18n/base/instances/TranslationMessage.html
Labels: cla-not-required, area/java-client

#2828 fix bug 2750: filter and <vip> tag can support customized vipconfig name
  src/main/java/com/vmware/vipclient/i18n/filters/VIPComponentFilter.java
  src/main/java/com/vmware/vipclient/i18n/filters/VIPPatternFilter.java
  src/main/java/com/vmware/vipclient/i18n/fmt/common/MessageSupport.java
  src/test/java/com/vmware/vip/i18n/VIPComponentFilterTest.java
  src/test/java/com/vmware/vip/i18n/VIPPatternFilterTest.java
Labels: area/java-client

#3061 fixed s3 config compatible
  g11n-ws/modules/md-data-api-s3impl/src/main/java/com/vmware/vip/messages/data/conf/S3Config.java
Labels: cla-not-required

#3071 upgrade the spring web
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required

#3073 upgrade spring web(0.6.x)
  g11n-ws/build.gradle
Labels: cla-not-required

#3092 upgrade spring boot
  g11n-ws/build.gradle
  g11n-ws/vip-manager-i18n/build.gradle
  g11n-ws/vip-manager-l10n/build.gradle
  g11n-ws/vip-manager-lite-i18n/build.gradle
Labels: cla-not-required
